const widths = [480, 960, 1600];

const responsivePath = (src, width) => {
  // CMS uploads are added directly to gh-pages at runtime, so they do not
  // have build-time responsive WebP derivatives. Keep their original URL.
  if (typeof src !== "string" || src.startsWith("/assets/admin-uploads/") || !src.startsWith("/assets/") || !/\.(png|jpe?g|webp)$/i.test(src)) return null;
  const stem = src.replace(/^\/assets\//, "").replace(/\.(png|jpe?g|webp)$/i, "");
  return `/assets/responsive/${stem}-${width}.webp`;
};

/**
 * Serves a suitably sized WebP on supported browsers while retaining the
 * original asset as a safe fallback. The responsive files are generated by
 * `npm run assets:responsive`.
 */
export function ResponsiveImage({ src, sizes = "100vw", loading = "lazy", decoding = "async", ...props }) {
  const srcSet = widths
    .map((width) => {
      const path = responsivePath(src, width);
      return path ? `${path} ${width}w` : null;
    })
    .filter(Boolean)
    .join(", ");

  return <img src={src} srcSet={srcSet || undefined} sizes={srcSet ? sizes : undefined} loading={loading} decoding={decoding} {...props} />;
}

export const responsiveImageUrl = (src, width = 1600) => responsivePath(src, width) || src;
