export const chapters = [
  { id: "about", label: "ABOUT", zh: "个人概览" },
  { id: "experience", label: "EXPERIENCE", zh: "职业经历" },
  { id: "wanying", label: "WANYING", zh: "万应低代码" },
  { id: "projects", label: "PROJECTS", zh: "代表项目" },
  { id: "graphic", label: "VISUAL", zh: "视觉设计" },
  { id: "vibe", label: "AI × DESIGN", zh: "AI 创作" },
];

export const career = [
  { version: "V1.0", role: "UI Designer", period: "2015—2017", note: "从视觉表达进入数字产品，建立界面与品牌基础。" },
  { version: "V2.0", role: "Product Interface Designer", period: "2018—2020", note: "深入业务流程，把复杂需求转译成清晰界面。" },
  { version: "V3.0", role: "Design System Builder", period: "2021—2023", note: "用组件、变量和规范支撑多业务线协作。" },
  { version: "V4.0", role: "UI Design Lead", period: "2024—NOW", note: "连接产品、设计与研发，推动体验标准落地。" },
];

export const systemModules = [
  {
    id: "tokens",
    index: "01",
    title: "Design Tokens / 设计令牌",
    caption: "Color / Type / Space / State",
    description: "建立颜色、字体、间距、圆角、阴影、状态与布局变量，让低代码平台拥有统一的体验语言。",
    detail: "变量按业务层级、组件状态和研发映射关系组织，减少重复沟通，让设计和代码能用同一套命名规则描述界面。",
    tags: ["Color Tokens", "Typography", "Spacing", "State Map"],
    image: "/assets/library/03-wanying/01-tokens/设计变量-dark.png",
    gallery: [
      "/assets/library/03-wanying/01-tokens/设计变量-dark.png",
      "/assets/library/03-wanying/01-tokens/设计变量-light.png",
      "/assets/library/03-wanying/01-tokens/基础颜色.png",
      "/assets/library/03-wanying/01-tokens/字体.png",
      "/assets/library/03-wanying/01-tokens/边框.png",
      "/assets/library/03-wanying/01-tokens/阴影.png",
      "/assets/library/03-wanying/01-tokens/设计原则.png",
      "/assets/library/03-wanying/01-tokens/ScreenShot_2026-06-20_125309_829.png",
      "/assets/library/03-wanying/01-tokens/ScreenShot_2026-06-20_125338_843.png",
    ],
  },
  {
    id: "components",
    index: "02",
    title: "Component Library / 组件库",
    caption: "Button / Table / Modal / Workflow",
    description: "沉淀覆盖后台、表单、流程、图表和低代码画布的组件库，支持状态、尺寸、权限和异常场景。",
    detail: "组件不是视觉资产堆叠，而是包含使用场景、边界规则、交互状态和研发验收标准的可复用产品语言。",
    tags: ["Default", "Hover", "Active", "Disabled", "Loading"],
    image: "/assets/library/03-wanying/02-components/Table表格.png",
    gallery: [
      "/assets/library/03-wanying/02-components/Button 按钮.png",
      "/assets/library/03-wanying/02-components/Input  输入框.png",
      "/assets/library/03-wanying/02-components/Select  选择器.png",
      "/assets/library/03-wanying/02-components/Table表格.png",
      "/assets/library/03-wanying/02-components/Form 表单.png",
      "/assets/library/03-wanying/02-components/Checkbox  多选.png",
      "/assets/library/03-wanying/02-components/Radio 单选.png",
      "/assets/library/03-wanying/02-components/Switch 开关.png",
      "/assets/library/03-wanying/02-components/Tabs 标签页.png",
      "/assets/library/03-wanying/02-components/Tag  标签.png",
      "/assets/library/03-wanying/02-components/Dropdown 下拉菜单.png",
      "/assets/library/03-wanying/02-components/Pagination 分页.png",
      "/assets/library/03-wanying/02-components/Steps 步骤条.png",
      "/assets/library/03-wanying/02-components/Progress 进度条.png",
      "/assets/library/03-wanying/02-components/Upload 上传.png",
      "/assets/library/03-wanying/02-components/Avatar 头像.png",
      "/assets/library/03-wanying/02-components/Breadcrumb 面包屑.png",
      "/assets/library/03-wanying/02-components/PageHeader 页头.png",
      "/assets/library/03-wanying/02-components/Image 图片.png",
      "/assets/library/03-wanying/02-components/Divider分割线.png",
      "/assets/library/03-wanying/02-components/TimePicker 时间选择器.png",
      "/assets/library/03-wanying/02-components/日期选择器 DatePicker.png",
      "/assets/library/03-wanying/02-components/导航.png",
    ],
  },
  {
    id: "editor",
    index: "03",
    title: "Visual Editor / 可视化编辑器",
    caption: "Material / Canvas / Inspector",
    description: "定义左侧物料、中间画布、右侧属性面板、顶部工具栏和图层结构的可视化编辑器体验。",
    detail: "重点处理拖拽吸附、属性同步、状态预览、页面发布和复杂组件配置，让低代码能力被普通业务用户理解。",
    tags: ["Drag", "Snap", "Preview", "Publish"],
    image: "/assets/library/03-wanying/03-editor/新增快速构建.png",
    gallery: [
      "/assets/library/03-wanying/03-editor/新增快速构建.png",
      "/assets/library/03-wanying/03-editor/动作设计器.jpg",
      "/assets/library/03-wanying/03-editor/数据流.jpg",
      "/assets/library/03-wanying/03-editor/新增SQL语句.jpg",
      "/assets/library/03-wanying/03-editor/SQL查询语句.png",
      "/assets/library/03-wanying/03-editor/变量.png",
      "/assets/library/03-wanying/03-editor/表格.png",
      "/assets/library/03-wanying/03-editor/运算符.png",
      "/assets/library/03-wanying/03-editor/更新日志.png",
      "/assets/library/03-wanying/03-editor/浅色外观-移动端.png",
    ],
  },
  {
    id: "admin",
    index: "04",
    title: "Admin Console / 管理后台",
    caption: "Application / Role / Workflow",
    description: "梳理应用管理、用户角色、权限、数据源、流程、发布和日志等后台信息架构。",
    detail: "通过树状导航、表格批量操作、权限状态和异常反馈，把复杂管理任务拆成稳定可学习的操作路径。",
    tags: ["Permission", "Data Source", "Publish", "Log"],
    image: "/assets/library/03-wanying/04-admin/工作台.png",
    gallery: [
      "/assets/library/03-wanying/04-admin/工作台.png",
      "/assets/library/03-wanying/04-admin/新版首页.png",
      "/assets/library/03-wanying/04-admin/业务逻辑.png",
      "/assets/library/03-wanying/04-admin/产品类型.png",
      "/assets/library/03-wanying/04-admin/数据模型设计器.png",
      "/assets/library/03-wanying/04-admin/界面开发.png",
      "/assets/library/03-wanying/04-admin/素材管理-图标-网格.png",
      "/assets/library/03-wanying/04-admin/素材管理-图片-网格.png",
      "/assets/library/03-wanying/04-admin/运维监控.png",
      "/assets/library/03-wanying/04-admin/高级.png",
      "/assets/library/03-wanying/04-admin/AI Agent.png",
    ],
  },
  {
    id: "governance",
    index: "05",
    title: "Governance / 设计治理",
    caption: "Review / Handoff / QA / Archive",
    description: "建立设计规范维护、组件命名、文件结构、评审流程、研发对接和设计验收标准。",
    detail: "治理部分确保团队并行交付时仍能保持一致性，让设计系统从一次性产物变成持续演进的组织能力。",
    tags: ["Review", "Handoff", "Design QA", "Versioning"],
    image: "/assets/library/03-wanying/05-governance/governance-new.png",
    gallery: [
      "/assets/library/03-wanying/05-governance/governance-new.png",
      "/assets/library/03-wanying/05-governance/0bb6a7e9-3e93-458c-88b6-26dbb557ea6d.png",
      "/assets/library/03-wanying/05-governance/1a9151d6-079f-471a-bafd-de0f2418a71a.png",
      "/assets/library/03-wanying/05-governance/2cec7238-96de-4de3-9752-9ead7f2f4639.png",
      "/assets/library/03-wanying/05-governance/34e9d0d9-196c-4909-9559-1f01ba8fdd67.png",
      "/assets/library/03-wanying/05-governance/4ed4e5cb-6e0f-4d0f-88f4-4fcaea9e6193.png",
      "/assets/library/03-wanying/05-governance/781d01eb-9d9c-40f2-992d-d3585db0cc9e.png",
      "/assets/library/03-wanying/05-governance/a42ad8a3-c67b-4cd2-8f39-5566b4c06b67.png",
      "/assets/library/03-wanying/05-governance/e8ca16a3-2c65-42b1-a80f-a19a79cb94a3.png",
      "/assets/library/03-wanying/05-governance/ef461c05-f49e-4ef7-ba7d-fd3ea9eb7722.png",
      "/assets/library/03-wanying/05-governance/fcb96bd6-678a-4471-ad65-46fea630565d.png",
    ],
  },
];

export const projects = [
  {
    id: "wanying",
    code: "WANYING",
    type: "ENTERPRISE LOW-CODE PLATFORM",
    title: "万应低代码平台设计系统",
    role: "Design System Lead / UI Design Lead",
    brief: "从 0 到 1 构建变量、组件、可视化编辑器、后台管理与治理流程。",
    image: "/assets/library/04-projects/01-wanying/cover/wanying.png",
    gallery: [
      "/assets/library/04-projects/01-wanying/gallery/设计变量-dark.png",
      "/assets/library/04-projects/01-wanying/gallery/Table表格.png",
      "/assets/library/04-projects/01-wanying/gallery/新增快速构建.png",
      "/assets/library/04-projects/01-wanying/gallery/新版首页.png",
      "/assets/library/04-projects/01-wanying/gallery/34e9d0d9-196c-4909-9559-1f01ba8fdd67.png",
    ],
    metrics: [["40+", "核心组件"], ["6", "系统模块"], ["30%", "重复设计减少"]],
    details: [
      ["背景", "多业务线并行开发，界面标准分散，设计还原与迭代成本持续升高。"],
      ["方法", "从 Token 切入，沉淀组件与核心交互，再建立评审、命名与归档机制。"],
      ["结果", "让设计系统从一次性交付变成持续演进、可被研发复用的组织能力。"],
    ],
  },
  {
    id: "admin",
    code: "ADMIN",
    type: "ENTERPRISE ADMIN CONSOLE",
    title: "企业级权限与流程管理平台",
    role: "Lead UI Designer",
    brief: "重构权限、组织架构、审批流程与数据表格体验。",
    image: "/assets/library/04-projects/02-admin/cover/admin.png",
    gallery: [
      "/assets/library/04-projects/02-admin/gallery/工作台.png",
      "/assets/library/04-projects/02-admin/gallery/业务逻辑.png",
      "/assets/library/04-projects/02-admin/gallery/数据模型设计器.png",
      "/assets/library/04-projects/02-admin/gallery/素材管理-图片-网格.png",
      "/assets/library/04-projects/02-admin/gallery/运维监控.png",
    ],
    metrics: [["12", "权限场景"], ["28", "页面模板"], ["22%", "路径缩短"]],
    details: [
      ["背景", "后台域多、权限交叉、信息层级松散，新老用户都容易在任务中迷路。"],
      ["方法", "重组信息架构与角色路径，统一权限矩阵、表格模式和异常状态。"],
      ["结果", "复杂管理任务被拆成清晰、稳定、可学习的操作路径。"],
    ],
  },
  {
    id: "mobile",
    code: "MOBILE",
    type: "MOBILE PRODUCT / MINI PROGRAM",
    title: "移动端服务小程序体验升级",
    role: "Product Interface Designer",
    brief: "围绕查询、任务、消息与转化，重构移动端核心路径。",
    image: "/assets/library/04-projects/03-mobile/cover/mobile.png",
    gallery: [
      "/assets/library/04-projects/03-mobile/gallery/mobile.png",
      "/assets/library/04-projects/03-mobile/gallery/浅色外观-移动端.png",
      "/assets/library/04-projects/03-mobile/gallery/变量.png",
      "/assets/library/04-projects/03-mobile/gallery/新增快速构建.png",
    ],
    metrics: [["3", "核心人群"], ["18%", "入口点击提升"], ["2.4×", "路径更清晰"]],
    details: [
      ["背景", "功能入口多、层级深，消息与任务割裂，关键转化路径被打断。"],
      ["方法", "以用户旅程和 3 类核心人群为起点，重排首页层级并统一任务入口。"],
      ["结果", "关键功能触达更短，回访后能更快回到原有任务上下文。"],
    ],
  },
];

export const works = [
  { src: "/assets/library/05-graphic/三星堆海报.png", title: "三星堆", type: "POSTER / CULTURE" },
  { src: "/assets/library/05-graphic/湘遇好礼海报.png", title: "湘遇好礼", type: "BRAND / CAMPAIGN" },
  { src: "/assets/library/05-graphic/佛像海报.png", title: "造像", type: "POSTER / CULTURE" },
  { src: "/assets/library/05-graphic/个人工作站loading页.png", title: "个人工作站", type: "MOTION / LOADING" },
  { src: "/assets/library/05-graphic/Frame 1041253.png", title: "视觉试验", type: "GRAPHIC / EDITORIAL" },
  { src: "/assets/library/05-graphic/image 134.png", title: "图形档案", type: "GRAPHIC / SYSTEM" },
  { src: "/assets/library/05-graphic/Frame 1041254.png", title: "版式练习", type: "EDITORIAL / TYPE" },
  { src: "/assets/library/05-graphic/Group 1321316532.png", title: "视觉切片 01", type: "GRAPHIC / ARCHIVE" },
  { src: "/assets/library/05-graphic/Group 1321316534.png", title: "视觉切片 02", type: "GRAPHIC / ARCHIVE" },
  { src: "/assets/library/05-graphic/Group 1321316535.png", title: "视觉切片 03", type: "GRAPHIC / ARCHIVE" },
  { src: "/assets/library/05-graphic/Group 1321316536.png", title: "视觉切片 04", type: "GRAPHIC / ARCHIVE" },
  { src: "/assets/library/05-graphic/Group 1321316537.png", title: "视觉切片 05", type: "GRAPHIC / ARCHIVE" },
  { src: "/assets/library/05-graphic/image 118.png", title: "影像实验", type: "IMAGE / STUDY" },
  { src: "/assets/library/05-graphic/image 138.png", title: "材质档案", type: "IMAGE / STUDY" },
];

export const vibeProjects = [
  {
    index: "01", code: "X-GZ", title: "小小馆长", subtitle: "成长记录 / 藏品策展 / 睡眠故事",
    tags: "WECHAT MINI-PROGRAM · AI · FAMILY", image: "/assets/library/06-vibe/01-xiaoxiaoguanzhang/audio-lab.png", mediaType: "image",
    wechat: { qr: "/assets/library/06-vibe/01-xiaoxiaoguanzhang/qrcode.png", hint: "微信搜索「小小馆长」立即体验" },
    description: "把孩子喜欢的东西变成博物馆藏品，基于藏品生成专属睡眠故事，支持童言、第一次、日志与策展记录。",
    background: "传统成长记录靠相册与日记，素材零散、缺少故事性，孩子的好奇心与童言随时间遗忘，无法被结构化保存与回看。",
    problem: "成长记录碎片化：照片散落相册，童言与第一次靠记忆，缺少把孩子视角的收藏转化为可回看、可策展叙事的工具。",
    solution: "以藏品为核心，记录童言、第一次与日常日志，AI 基于藏品生成专属睡眠故事，支持 3D 化藏品与访问朋友博物馆。",
    stack: ["微信小程序", "Three.js", "LLM API", "云开发"],
    highlights: ["藏品化记录孩子喜好", "基于藏品生成专属睡眠故事", "童言 / 第一次 / 日志结构化沉淀", "3D 藏品与跨朋友博物馆互访"],
    link: "#",
  },
  {
    index: "02", code: "V-ALC", title: "声纹炼金炉", subtitle: "人声训练 / 声纹替换 / 母带翻唱",
    tags: "WEB AUDIO · AI VOICE · ENTERTAINMENT", image: "/assets/library/06-vibe/02-travel-archive/travel-archive.png", mediaType: "image",
    description: "PC 端网页娱乐工具，训练个人人声模型，对歌曲提取人声、声纹替换并后期母带，生成翻唱作品。",
    background: "想用自己的声音翻唱喜欢的歌，但传统流程要在宿主软件里手动对轨、调效果器，还需要本地部署 AI 模型，门槛高且碎片化。",
    problem: "翻唱链路割裂：人声提取、声纹训练、替换、母带各用不同工具，参数无法互通，普通用户难以独立完成一首翻唱。",
    solution: "在浏览器内串联人声训练→歌曲分离→声纹替换→母带后期→导出全流程，每步参数保留可回溯，降低翻唱门槛。",
    stack: ["React", "Web Audio API", "Python AI", "FFmpeg.wasm"],
    highlights: ["录制并训练个人人声模型", "一键分离歌曲人声与伴奏", "声纹替换实时预览对比", "母带后期与多版本导出"],
    link: "#",
  },
  {
    index: "03", code: "M-HANG", title: "墨航 · 文学实验室", subtitle: "小说创作 / AI 自动写作 / 本地优先",
    tags: "AI · LITERATURE · FULL-STACK", image: "/assets/library/06-vibe/03-pixel-alchemy/pixel-alchemy.png", mediaType: "image",
    description: "面向创作者的小说创作工作台，整合项目管理、创作中心、PRD 文档与 AI 自动写作，本地优先、数据自持。",
    background: "写作者在使用通用文档工具时，创作素材、大纲、设定、章节散落各处，AI 辅助写作只能片段生成，无法贯穿整本小说的设定与连续性。",
    problem: "创作工具割裂：项目管理、正文写作、设定维护与 AI 生成各用一套，设定无法跨章节复用，AI 不理解既有世界观，长篇连贯性难维护。",
    solution: "以工作台为核心，整合小说项目、创作中心、PRD 文档与设置，AI Agent 基于本地设定自动续写，保证世界观一致与创作链路完整。",
    stack: ["React", "Node.js", "SQLite", "LLM API"],
    highlights: ["工作台统一管理多本小说项目", "创作中心与设定文档联动", "AI Agent 基于本地设定自动续写", "本地优先，数据自持可离线"],
    link: "https://mohang.zenslab.top",
  },
  {
    index: "04", code: "S-LJ", title: "食旅集", subtitle: "菜单识别 / 可视化点单 / 跨语言点餐",
    tags: "AI · TRAVEL · FULL-STACK", image: "/assets/library/06-vibe/04-shilvji/image-bureau.png", mediaType: "image",
    description: "拍下外文菜单，AI 识别分类、匹配图片、换算价格，生成可视化中文点单界面。",
    background: "去国外旅行吃饭时，菜单全是外文，菜名看不懂、价格要换算、不知道长什么样，只能靠猜或随便指，点餐体验紧张又低效。",
    problem: "语言障碍 + 信息缺失：外文菜名无法理解，缺少菜品图片参考，价格需心算换算，点完无法确认，与服务员沟通成本高。",
    solution: "拍下菜单 → AI 识别菜品并分类 → 自动搜索对应图片 → 生成带中文名、换算价格的可视化菜单 → 勾选提交小票单，全程不靠口语沟通。",
    stack: ["React", "Node.js", "OCR / Vision API", "Tailwind"],
    highlights: ["菜单拍照即识别分类", "自动匹配菜品参考图", "中文名称与汇率换算价格", "点单小票一键提交服务员"],
    link: "https://slj.zenslab.top",
  },
];
