export const chapters = [
  { id: "about", label: "ABOUT", zh: "个人概览" },
  { id: "experience", label: "EXPERIENCE", zh: "职业经历" },
  { id: "wanying", label: "WANYING", zh: "万应低代码" },
  { id: "projects", label: "PROJECTS", zh: "代表项目" },
  { id: "graphic", label: "VISUAL", zh: "视觉设计" },
  { id: "vibe", label: "AI × DESIGN", zh: "AI 创作" },
];

export const profile = {
  heroName: "ZEN.TANG",
  heroRole: "Product Designer · Designer & Builder",
  heroLine: "10+ 年产品体验设计师，从产品构想、设计系统到可运行产品，把设计判断推进到真正落地。",
  heroTags: ["Product Design", "Design System", "AI × Builder"],
  cta: "VIEW FULL PROFILE / 查看完整档案",
  stats: [
    ["10+", "年产品体验与设计实践"],
    ["0→1", "从构想到可运行产品落地"],
    ["MULTI", "B 端 · AI · 移动端 · 数据可视化"],
  ],
  info: [
    ["姓名", "唐启东"],
    ["所在地", "长沙 / 中国"],
    ["职业", "Product Designer"],
    ["经验", "10+ Years"],
    ["方向", "B 端 · AI · 移动端 · 数据可视化"],
    ["邮箱", "zen92@foxmail.com"],
  ],
  philosophy: {
    lead: "多数设计师的边界停在原型与交付，我的边界是：产品构想 → 结构与流程 → 视觉系统 → AI 与代码实现 → 可运行产品。",
    pillars: [
      { icon: "ux", title: "用户体验", en: "UX", desc: "从真实场景出发，解决复杂产品问题，而非只做视觉表达。" },
      { icon: "product", title: "产品思维", en: "Product", desc: "关注业务目标与用户任务，让设计服务于产品而非停在界面。" },
      { icon: "tech", title: "技术落地", en: "Build", desc: "通过 AI 与代码，把设计推进到可运行、可验证的产品。" },
    ],
  },
  capabilities: [
    { icon: "product", group: "Product Design", items: ["用户体验设计", "信息架构", "产品流程设计", "复杂系统设计"] },
    { icon: "visual", group: "Visual Design", items: ["品牌视觉", "KV 设计", "3D 视觉", "插画设计"] },
    { icon: "ai", group: "AI Product", items: ["AI 产品设计", "Prompt Engineering", "AI 工作流", "Vibe Coding"] },
    { icon: "system", group: "System Design", items: ["Design System", "Component Library", "Design Token"] },
  ],
  timeline: [
    ["2015", "进入 UI 设计领域", "建立视觉与界面基础"],
    ["2018", "深入企业级产品", "从视觉执行走向业务与信息架构"],
    ["2021", "负责复杂 B 端系统与数据平台", "主导设计系统建设"],
    ["2024", "探索 AI 产品与智能化流程", "从设计稿走向 AI 与代码实现"],
    ["2026", "独立构建可运行产品", "产品构想 → 设计 → 落地的完整闭环"],
  ],
  workflow: ["Research", "Define", "Design", "Prototype", "Code", "Validate"],
  workflowDesc: "多数 UI 的边界停在原型 → 设计稿 → 开发交付。我把它推进到：产品构想 → 结构与流程 → 视觉系统 → AI 与代码实现 → 可运行产品。",
  stack: [
    { group: "Design", items: ["Figma", "Adobe", "C4D"] },
    { group: "AI", items: ["ChatGPT", "Claude", "Midjourney", "ComfyUI"] },
    { group: "Development", items: ["React", "Three.js", "TypeScript", "Tailwind"] },
  ],
  beyond: [
    { icon: "travel", title: "Travel", desc: "探索不同文化与视觉语言" },
    { icon: "music", title: "Music", desc: "AI 音乐实验与声音设计" },
    { icon: "photo", title: "Photography", desc: "记录城市与自然瞬间" },
    { icon: "rocket", title: "AI Exploration", desc: "持续探索新工具和创造方式" },
  ],
  signature: "Designer × Builder",
};

export const career = [
  {
    version: "V1.0",
    role: "UI Designer",
    period: "2015—2017",
    note: "从视觉表达进入数字产品，建立界面与品牌基础。",
    stage: "FOUNDATION",
    en: "Visual Foundation",
    keyword: "视觉",
    overview: "从视觉设计切入数字产品，建立对界面层级、排版节奏与品牌一致性的基础认知，把抽象的视觉判断转化为可复用的界面语言。",
    focus: ["视觉表达", "界面排版", "品牌延展", "基础交互"],
    deliveries: ["基础色彩 / 字体 / 栅格规范", "Web 与移动端界面视觉交付", "品牌视觉延展至运营物料"],
    lesson: "学会用视觉解决「看起来对」的问题，但开始意识到界面背后还有更深的逻辑。",
    shift: "从「画好看的界面」走向「理解界面背后的逻辑」",
  },
  {
    version: "V2.0",
    role: "Product Interface Designer",
    period: "2018—2020",
    note: "深入业务流程，把复杂需求转译成清晰界面。",
    stage: "BUSINESS",
    en: "Product Thinking",
    keyword: "业务",
    overview: "从视觉执行深入业务流程，把复杂需求拆解成清晰的信息架构与任务路径，让界面真正服务于用户目标而非只是好看。",
    focus: ["业务理解", "信息架构", "任务流程", "可用性"],
    deliveries: ["多业务域导航与角色路径梳理", "复杂审批与表单流程化", "基于任务场景的可用性优化"],
    lesson: "界面是结果，业务与任务才是起点；先定义问题，再定义界面。",
    shift: "从「画界面」走向「定义问题与任务路径」",
  },
  {
    version: "V3.0",
    role: "Design System Builder",
    period: "2021—2023",
    note: "用组件、变量和规范支撑多业务线协作。",
    stage: "SYSTEM",
    en: "System Building",
    keyword: "系统",
    overview: "从单个项目上升到系统层面，用 Token、组件与规范支撑多业务线并行交付，让设计从一次性产物变成可被研发复用的组织能力。",
    focus: ["系统抽象", "组件体系", "研发协同", "治理流程"],
    deliveries: ["Token 体系：颜色 / 字体 / 间距 / 状态", "40+ 组件库与状态规范", "评审 / 命名 / 归档治理流程"],
    lesson: "设计系统的价值不在组件数量，而在它能否被研发真正复用并持续演进。",
    shift: "从「做项目」走向「建系统」",
  },
  {
    version: "V4.0",
    role: "Designer & Builder",
    period: "2024—NOW",
    note: "从设计稿走向 AI 与代码，独立构建可运行产品。",
    stage: "BUILDER",
    en: "Product Builder",
    keyword: "落地",
    overview: "不再停在原型与交付，而是从产品构想出发，用 AI 与代码把设计判断推进到可运行、可验证的产品，打通产品 → 设计 → 落地的完整闭环。",
    focus: ["AI 产品设计", "Vibe Coding", "可运行产品", "设计到落地"],
    deliveries: ["从构想到可运行产品的独立构建", "AI 驱动的设计与开发流程", "产品 / 设计 / 代码的完整闭环"],
    lesson: "设计的终点不是交付稿，而是让正确的产品判断真正跑起来。",
    shift: "从「交付设计稿」走向「交付可运行产品」",
  },
];

export const systemModules = [
  {
    id: "tokens",
    index: "01",
    title: "Design Tokens / 设计令牌",
    tabLabel: "设计令牌",
    tabEn: "Design Tokens",
    caption: "Color / Type / Space / State",
    description: "颜色、字体、间距、状态变量，让设计与代码用同一套命名描述界面。",
    detail: "变量按业务层级与研发映射组织，减少重复沟通。",
    tags: ["Color Tokens", "Typography", "Spacing", "State Map"],
    image: "/assets/library/03-wanying/01-tokens/设计变量-dark.webp",
    gallery: [
      "/assets/library/03-wanying/01-tokens/设计变量-dark.webp",
      "/assets/library/03-wanying/01-tokens/设计变量-light.webp",
      "/assets/library/03-wanying/01-tokens/基础颜色.webp",
      "/assets/library/03-wanying/01-tokens/字体.webp",
      "/assets/library/03-wanying/01-tokens/边框.webp",
      "/assets/library/03-wanying/01-tokens/阴影.webp",
      "/assets/library/03-wanying/01-tokens/设计原则.webp",
      "/assets/library/03-wanying/01-tokens/ScreenShot_2026-06-20_125309_829.webp",
      "/assets/library/03-wanying/01-tokens/ScreenShot_2026-06-20_125338_843.webp",
    ],
  },
  {
    id: "components",
    index: "02",
    title: "Component Library / 组件库",
    tabLabel: "组件库",
    tabEn: "Components",
    caption: "Button / Table / Modal / Workflow",
    description: "覆盖后台、表单、流程、图表与低代码画布的组件库，含状态与边界规范。",
    detail: "组件是含使用场景、交互状态与验收标准的可复用产品语言。",
    tags: ["Default", "Hover", "Active", "Disabled", "Loading"],
    image: "/assets/library/03-wanying/02-components/Table表格.webp",
    gallery: [
      "/assets/library/03-wanying/02-components/Button 按钮.webp",
      "/assets/library/03-wanying/02-components/Input  输入框.webp",
      "/assets/library/03-wanying/02-components/Select  选择器.webp",
      "/assets/library/03-wanying/02-components/Table表格.webp",
      "/assets/library/03-wanying/02-components/Form 表单.webp",
      "/assets/library/03-wanying/02-components/Checkbox  多选.webp",
      "/assets/library/03-wanying/02-components/Radio 单选.webp",
      "/assets/library/03-wanying/02-components/Switch 开关.webp",
      "/assets/library/03-wanying/02-components/Tabs 标签页.webp",
      "/assets/library/03-wanying/02-components/Tag  标签.webp",
      "/assets/library/03-wanying/02-components/Dropdown 下拉菜单.webp",
      "/assets/library/03-wanying/02-components/Pagination 分页.webp",
      "/assets/library/03-wanying/02-components/Steps 步骤条.webp",
      "/assets/library/03-wanying/02-components/Progress 进度条.webp",
      "/assets/library/03-wanying/02-components/Upload 上传.webp",
      "/assets/library/03-wanying/02-components/Avatar 头像.webp",
      "/assets/library/03-wanying/02-components/Breadcrumb 面包屑.webp",
      "/assets/library/03-wanying/02-components/PageHeader 页头.webp",
      "/assets/library/03-wanying/02-components/Image 图片.webp",
      "/assets/library/03-wanying/02-components/Divider分割线.webp",
      "/assets/library/03-wanying/02-components/TimePicker 时间选择器.webp",
      "/assets/library/03-wanying/02-components/日期选择器 DatePicker.webp",
      "/assets/library/03-wanying/02-components/导航.webp",
    ],
  },
  {
    id: "editor",
    index: "03",
    title: "Visual Editor / 可视化编辑器",
    tabLabel: "可视化编辑器",
    tabEn: "Visual Editor",
    caption: "Material / Canvas / Inspector",
    description: "物料、画布、属性面板、工具栏与图层结构的可视化编辑器体验。",
    detail: "拖拽吸附、属性同步、状态预览与发布，让低代码被普通用户理解。",
    tags: ["Drag", "Snap", "Preview", "Publish"],
    image: "/assets/library/03-wanying/03-editor/新增快速构建.webp",
    gallery: [
      "/assets/library/03-wanying/03-editor/新增快速构建.webp",
      "/assets/library/03-wanying/03-editor/动作设计器.jpg",
      "/assets/library/03-wanying/03-editor/数据流.jpg",
      "/assets/library/03-wanying/03-editor/新增SQL语句.jpg",
      "/assets/library/03-wanying/03-editor/SQL查询语句.webp",
      "/assets/library/03-wanying/03-editor/变量.webp",
      "/assets/library/03-wanying/03-editor/表格.webp",
      "/assets/library/03-wanying/03-editor/运算符.webp",
      "/assets/library/03-wanying/03-editor/更新日志.webp",
      "/assets/library/03-wanying/03-editor/浅色外观-移动端.webp",
    ],
  },
  {
    id: "admin",
    index: "04",
    title: "Admin Console / 管理后台",
    tabLabel: "管理后台",
    tabEn: "Admin Console",
    caption: "Application / Role / Workflow",
    description: "应用管理、角色权限、数据源、流程与日志的后台信息架构。",
    detail: "树状导航与表格批量操作，把复杂任务拆成可学习路径。",
    tags: ["Permission", "Data Source", "Publish", "Log"],
    image: "/assets/library/03-wanying/04-admin/工作台.webp",
    gallery: [
      "/assets/library/03-wanying/04-admin/工作台.webp",
      "/assets/library/03-wanying/04-admin/新版首页.webp",
      "/assets/library/03-wanying/04-admin/业务逻辑.webp",
      "/assets/library/03-wanying/04-admin/产品类型.webp",
      "/assets/library/03-wanying/04-admin/数据模型设计器.webp",
      "/assets/library/03-wanying/04-admin/界面开发.webp",
      "/assets/library/03-wanying/04-admin/素材管理-图标-网格.webp",
      "/assets/library/03-wanying/04-admin/素材管理-图片-网格.webp",
      "/assets/library/03-wanying/04-admin/运维监控.webp",
      "/assets/library/03-wanying/04-admin/高级.webp",
      "/assets/library/03-wanying/04-admin/AI Agent.webp",
    ],
  },
  {
    id: "governance",
    index: "05",
    title: "Governance / 设计治理",
    tabLabel: "设计治理",
    tabEn: "Governance",
    caption: "Review / Handoff / QA / Archive",
    description: "规范维护、命名、评审流程、研发对接与设计验收标准。",
    detail: "确保并行交付时保持一致，让系统持续演进。",
    tags: ["Review", "Handoff", "Design QA", "Versioning"],
    image: "/assets/library/03-wanying/05-governance/governance-new.webp",
    gallery: [
      "/assets/library/03-wanying/05-governance/governance-new.webp",
      "/assets/library/03-wanying/05-governance/0bb6a7e9-3e93-458c-88b6-26dbb557ea6d.webp",
      "/assets/library/03-wanying/05-governance/1a9151d6-079f-471a-bafd-de0f2418a71a.webp",
      "/assets/library/03-wanying/05-governance/2cec7238-96de-4de3-9752-9ead7f2f4639.webp",
      "/assets/library/03-wanying/05-governance/34e9d0d9-196c-4909-9559-1f01ba8fdd67.webp",
      "/assets/library/03-wanying/05-governance/4ed4e5cb-6e0f-4d0f-88f4-4fcaea9e6193.webp",
      "/assets/library/03-wanying/05-governance/781d01eb-9d9c-40f2-992d-d3585db0cc9e.webp",
      "/assets/library/03-wanying/05-governance/a42ad8a3-c67b-4cd2-8f39-5566b4c06b67.webp",
      "/assets/library/03-wanying/05-governance/e8ca16a3-2c65-42b1-a80f-a19a79cb94a3.webp",
      "/assets/library/03-wanying/05-governance/ef461c05-f49e-4ef7-ba7d-fd3ea9eb7722.webp",
      "/assets/library/03-wanying/05-governance/fcb96bd6-678a-4471-ad65-46fea630565d.webp",
    ],
  },
];

const mysteryProject = {
  id: "enter-the-case",
  code: "ENTER THE CASE",
  type: "MOBILE PRODUCT / MURDER MYSTERY",
  title: "入局｜剧本杀社交体验设计",
  role: "Product Strategy / UX Lead / Visual System",
  brief: "从选本、组局到到店履约，打造完整的剧本杀消费决策与社交体验。",
  image: "/assets/library/04-projects/01-mystery-app/cover/mystery-app-cover.webp",
  caseStyle: "mobile",
  gallery: [
    "/assets/library/04-projects/01-mystery-app/gallery/01-home.webp",
    "/assets/library/04-projects/01-mystery-app/gallery/02-onboarding.webp",
    "/assets/library/04-projects/01-mystery-app/gallery/03-script-library.webp",
    "/assets/library/04-projects/01-mystery-app/gallery/04-filter-results.webp",
    "/assets/library/04-projects/01-mystery-app/gallery/05-ranking.webp",
    "/assets/library/04-projects/01-mystery-app/gallery/06-script-detail.webp",
    "/assets/library/04-projects/01-mystery-app/gallery/07-store-list.webp",
    "/assets/library/04-projects/01-mystery-app/gallery/08-store-detail.webp",
    "/assets/library/04-projects/01-mystery-app/gallery/09-session-schedule.webp",
    "/assets/library/04-projects/01-mystery-app/gallery/10-booking-confirm.webp",
  ],
  metrics: [["10", "核心界面"], ["3", "关键角色"], ["5→3", "决策步骤"]],
  meta: {
    type: "移动端 App / O2O 娱乐社交",
    role: "产品策略、用户体验、视觉系统",
    period: "8 周产品设计",
    status: "完整产品案例",
    year: "2026",
  },
  overview: "入局是一套面向剧本杀玩家、DM 与门店的移动端产品。它把‘选什么、和谁玩、去哪玩、如何确认’四段割裂决策收拢为可理解、可比较、可完成的一条任务链。",
  background: "剧本杀玩家面对丰富的剧本、榜单与门店内容，但内容口径不统一，往往需要在平台、微信群与电话之间反复确认；新用户尤其难以判断剧本是否适合自己，也缺少对门店、DM 与同场玩家的稳定信任。",
  pains: [
    { tag: "PAIN 01", title: "选本信息很多，决策依据却很少", desc: "题材、人数、时长与难度分散呈现，评分又缺乏玩家经验和场景背景，新用户看得多、选得慢。" },
    { tag: "PAIN 02", title: "组局与预约跨越多个渠道", desc: "门店档期、DM、参与人和价格需要通过聊天或电话二次确认，任何一处变化都会让订单上下文丢失。" },
    { tag: "PAIN 03", title: "体验在散场后立刻中断", desc: "评价、复盘和同场关系没有被妥善承接，优质内容难沉淀，玩家也难形成持续回访。" },
  ],
  goal: "建立一条从‘按约束发现剧本’到‘可信决策、完成组局、到店履约’的闭环，同时用防剧透机制承接评价与社区内容。",
  research: [
    { method: "利益相关者访谈", sample: "5 家门店 / 8 位 DM", finding: "档期与参与人变化是履约风险的主要来源，门店需要更早获得稳定订单信息。" },
    { method: "玩家情境访谈", sample: "16 位新老玩家", finding: "新玩家先看人数、时长与氛围，老玩家才会进一步关注作者、机制与复玩价值。" },
    { method: "任务走查", sample: "18 条选本与预约路径", finding: "从发现剧本到确认场次平均跨越 5 个决策节点，其中 2 个发生在平台之外。" },
    { method: "卡片分类", sample: "24 份概念样本", finding: "用户更容易按‘今晚想获得什么体验’理解内容，而不是按发行分类理解内容。" },
  ],
  insights: [
    "发现页应先回应时间、人数与情绪目标，再逐步暴露专业剧本标签。",
    "评分必须带上玩家经验、门店与 DM 上下文，才能成为可信决策证据。",
    "预约不是一个按钮，而是一段需要持续同步参与人、场次和政策的协作流程。",
  ],
  contribution: "以资深产品设计师视角负责从问题定义到高保真方案的完整闭环：重组信息架构与任务流，建立内容标签和评价可信度模型，定义移动端 Token 与组件规范，并将发现、详情、门店、场次和订单 10 个核心界面统一到同一套产品语言中。",
  contributionTags: ["产品策略", "研究框架", "信息架构", "任务流", "移动端 UI", "组件规范", "视觉系统"],
  contributionSplit: [
    { label: "策略与研究", value: 24 },
    { label: "信息架构与流程", value: 28 },
    { label: "交互与原型", value: 26 },
    { label: "视觉系统与交付", value: 22 },
  ],
  coreDesign: [
    { problem: "用户被海量剧本和专业标签淹没", insight: "人们先按约束和期待做选择", solution: "首页先提供城市、人数、时长与情绪化精选，再在剧本库中逐层展开类型、难度和发行属性。", impact: "决策从 5 步压缩为 3 步" },
    { problem: "评分无法解释适不适合自己", insight: "评价的上下文比平均分更重要", solution: "把玩家经验、是否玩过、门店与 DM 作为评价背景，并用防剧透遮罩区分观点和剧情信息。", impact: "建立可解释的信任" },
    { problem: "门店、场次、参与人反复确认", insight: "组局本质是多人协作型订单", solution: "将日期、DM、剩余席位、参与人、取消政策与价格收进同一张持续更新的订单票券。", impact: "减少跨渠道确认" },
    { problem: "文化感容易变成装饰堆叠", insight: "品牌气质应服务信息层级", solution: "以暖黑、象牙白、朱砂红和低饱和金建立 Token，用票券切口、纸张肌理和电影光影表达剧场感。", impact: "形成统一且可扩展的品牌系统" },
  ],
  principles: [
    { title: "约束优先", desc: "先解决今晚能不能玩，再讨论想玩什么。" },
    { title: "信任可解释", desc: "让每个评分、状态和价格都有清晰来源。" },
    { title: "上下文不断裂", desc: "从发现到付款始终保留同一局游戏的信息。" },
    { title: "氛围不牺牲效率", desc: "电影感只强化关键节点，不遮挡任务。" },
  ],
  timeline: [
    { phase: "DISCOVER", title: "定义问题", desc: "访谈、任务走查与竞品拆解，建立玩家—DM—门店三方地图。" },
    { phase: "FRAME", title: "重组路径", desc: "将选本、选店、选场次和组局重组为一条连续任务流。" },
    { phase: "DESIGN", title: "系统化设计", desc: "建立移动端 Token、卡片、标签、票券、评价与订单组件。" },
    { phase: "VALIDATE", title: "可用性验证", desc: "围绕新手选本与多人预约进行任务走查并收敛信息密度。" },
  ],
  stack: ["Figma", "FigJam", "User Flow", "Design Tokens", "Prototype", "Usability Test"],
  capabilities: [
    { label: "产品策略", value: 94 },
    { label: "研究分析", value: 88 },
    { label: "交互设计", value: 94 },
    { label: "视觉系统", value: 92 },
    { label: "落地协同", value: 90 },
  ],
  outcome: "完成覆盖发现、筛选、榜单、剧本详情、门店、场次与订单的 10 个核心界面，并沉淀一套可继续扩展到社区、消息和个人中心的移动端视觉系统。任务走查中，核心预约决策由 5 个节点收敛为 3 个连续步骤。",
  outcomeBars: [
    { label: "核心任务覆盖", value: 92, caption: "10 个界面" },
    { label: "组件一致性", value: 94, caption: "统一 Token" },
    { label: "决策路径收敛", value: 82, caption: "5 → 3 步" },
    { label: "三方信息闭环", value: 88, caption: "玩家 / DM / 门店" },
  ],
  details: [
    ["背景", "选本、组局与门店履约长期分散在多个渠道，用户难以形成连续决策。"],
    ["方法", "用研究框架重组信息架构，再以同一套组件系统覆盖完整预约链路。"],
    ["结果", "形成 10 个关键界面、一条连续任务流和一套可扩展的移动端品牌系统。"],
  ],
};

const cdezProject = {
  id: "cdez-platform",
  code: "CDEZ INTELLIGENCE",
  type: "B2B PLATFORM / INDUSTRIAL PARK",
  title: "经开智域｜长沙经开区一体化平台",
  role: "Product Strategy / UX Lead / Data Experience",
  brief: "把招商、企业服务、工单、巡检、风险与经营分析汇入同一套园区运营工作台。",
  image: "/assets/library/04-projects/02-cdez-platform/ai-cover/cdez-cover.webp",
  caseStyle: "admin",
  gallery: [
    "/assets/library/04-projects/02-cdez-platform/ai-gallery/01-workbench.webp",
    "/assets/library/04-projects/02-cdez-platform/ai-gallery/02-investment-map.webp",
    "/assets/library/04-projects/02-cdez-platform/ai-gallery/03-leads.webp",
    "/assets/library/04-projects/02-cdez-platform/ai-gallery/04-customer-detail.webp",
    "/assets/library/04-projects/02-cdez-platform/ai-gallery/05-enterprise-profile.webp",
    "/assets/library/04-projects/02-cdez-platform/ai-gallery/06-work-orders.webp",
    "/assets/library/04-projects/02-cdez-platform/ai-gallery/07-inspection.webp",
    "/assets/library/04-projects/02-cdez-platform/ai-gallery/08-risk-warning.webp",
    "/assets/library/04-projects/02-cdez-platform/ai-gallery/09-finance.webp",
    "/assets/library/04-projects/02-cdez-platform/ai-gallery/10-permissions.webp",
  ],
  metrics: [["10", "核心业务界面"], ["9", "运营业务域"], ["24", "关键任务路径"]],
  meta: { type: "园区一体化运营平台", role: "产品策略 / 体验设计负责人", period: "5 个月", status: "完整平台案例", year: "2024" },
  overview: "面向长沙经开区集团及园区运营团队的一体化管理平台。项目将分散在部门、台账与线下沟通中的招商、企业服务、工单处置、巡检、风险预警和经营分析统一到可追踪的数字工作台，让管理者看全局、业务人员做任务、服务人员闭环问题。",
  background: "园区业务不是单一后台：管理层关注经营态势，招商团队关注线索与企业，服务团队关注诉求与工单，巡检人员关注现场处置。原有系统各自成岛，同一企业在不同模块拥有多套口径，跨部门协作依赖表格、群聊和人工催办。",
  pains: [
    { tag: "PAIN 01", title: "数据分散，管理层难以形成同一判断", desc: "招商、企服、物业和财务数据分别维护，指标口径与更新时间不同，经营会前需要大量人工汇总。" },
    { tag: "PAIN 02", title: "角色众多，通用首页无法支撑真实任务", desc: "管理者、招商主管、企服专员与巡检人员关注对象和操作频率不同，同一导航造成信息过载。" },
    { tag: "PAIN 03", title: "事件有记录，却没有完整闭环", desc: "企业诉求、巡检问题与风险预警缺少统一责任人、时限、升级和回访机制，状态常停留在处理中。" },
  ],
  goal: "以企业与事件为两条主线建立统一业务底座：让每个角色进入系统就看到该做的事，让每条数据能追溯来源，让每个问题从发现、派发、处理到复盘都有闭环。",
  research: [
    { method: "干系人访谈", sample: "12 个业务部门", finding: "各部门并不缺数据，真正缺少的是共同对象、统一口径和跨部门责任链。" },
    { method: "任务跟随", sample: "24 条关键流程", finding: "高频任务被重复录入和线下确认打断，异常路径比标准路径更消耗时间。" },
    { method: "角色卡片分类", sample: "18 位一线用户", finding: "工作台必须按角色重排信息，而不是按系统模块平均分配入口。" },
    { method: "字段盘点", sample: "320+ 业务字段", finding: "以企业主档和事件主档统一字段后，跨域查询与指标解释才具备基础。" },
  ],
  insights: [
    "园区平台的首页不是数据大屏，而是角色化的行动清单与异常提醒。",
    "企业档案必须串起招商、合同、服务、风险和经营信息，成为跨部门共同上下文。",
    "所有事件都需要责任人、时限、升级规则和处理证据，才能形成真正的运营闭环。",
  ],
  contribution: "负责从业务梳理、对象建模到高保真交付的完整设计工作：定义企业与事件双主线信息架构，建立九类角色工作台和指标分层，统一高密度表格、筛选、状态、批量操作与预警模式，并与产品、业务及研发共同完成关键流程验收。",
  contributionTags: ["业务建模", "角色工作台", "数据体验", "复杂表格", "流程闭环", "设计规范"],
  contributionSplit: [
    { label: "业务研究与建模", value: 28 },
    { label: "架构与任务流程", value: 27 },
    { label: "数据体验与交互", value: 25 },
    { label: "视觉规范与交付", value: 20 },
  ],
  coreDesign: [
    { problem: "所有角色共用同一套首页", insight: "岗位差异决定信息优先级", solution: "以角色任务、待办时限和风险等级组织工作台，并允许管理者切换全局视角。", impact: "首页从入口集合变成行动中枢" },
    { problem: "企业信息散落在多个业务域", insight: "企业是园区运营的共同主对象", solution: "建立企业 360° 档案，把招商阶段、合同、诉求、工单、风险与经营指标收进连续时间线。", impact: "跨部门查询上下文完整" },
    { problem: "高密度表格难扫读、难批量处理", insight: "B 端效率来自稳定模式与可预期反馈", solution: "统一筛选区、列设置、状态语义、批量动作和异常反馈，按任务暴露必要密度。", impact: "高频操作路径更短" },
    { problem: "问题状态可见但责任不清", insight: "闭环的核心是责任链而非状态标签", solution: "为工单、巡检和风险事件统一负责人、SLA、升级、证据与回访节点。", impact: "事件能够持续追踪和复盘" },
  ],
  principles: [
    { title: "角色先于模块", desc: "先回答谁在什么时刻要做什么，再决定系统入口。" },
    { title: "对象贯穿全域", desc: "以企业和事件保持跨部门上下文连续。" },
    { title: "密度服务决策", desc: "数据多不等于信息多，优先突出异常与行动。" },
    { title: "状态必须闭环", desc: "每个状态都对应责任、时限、证据和下一步。" },
  ],
  timeline: [
    { phase: "DISCOVER", title: "业务共识", desc: "访谈部门与一线岗位，梳理对象、指标和真实任务。" },
    { phase: "MODEL", title: "对象建模", desc: "统一企业、事件、组织与指标口径，搭建业务地图。" },
    { phase: "DESIGN", title: "场景设计", desc: "完成工作台、档案、工单、巡检、预警与经营分析。" },
    { phase: "DELIVER", title: "规范与验收", desc: "沉淀表格和状态规范，围绕关键路径完成研发验收。" },
  ],
  stack: ["Figma", "FigJam", "Service Blueprint", "Data Model", "Design Tokens", "Prototype"],
  capabilities: [
    { label: "业务抽象", value: 95 }, { label: "信息架构", value: 94 }, { label: "数据体验", value: 93 }, { label: "交互设计", value: 91 }, { label: "协同落地", value: 92 },
  ],
  outcome: "形成覆盖九个运营业务域的标准 B 端体验：10 个核心界面统一企业、事件、角色与指标语言，24 条关键任务路径拥有明确状态和异常反馈，高密度业务在同一套视觉与交互规范下保持稳定、清晰和可扩展。",
  outcomeBars: [
    { label: "业务域覆盖", value: 90, caption: "9 个业务域" },
    { label: "关键路径闭环", value: 94, caption: "24 条路径" },
    { label: "字段口径统一", value: 88, caption: "320+ 字段" },
    { label: "角色工作台", value: 92, caption: "9 类角色" },
  ],
  details: [["背景", "园区业务跨部门、跨系统运行，数据口径和责任链难以统一。"], ["方法", "以企业和事件为主对象，按角色任务组织工作台与业务闭环。"], ["结果", "完成 10 个核心界面及一套可扩展的标准 B 端数据体验规范。"]],
};

const wanyingSiteProject = {
  id: "wanying-site",
  code: "WANYING WEBSITE",
  type: "OFFICIAL WEBSITE / LOW-CODE",
  title: "万应工场｜企业低代码平台官网",
  role: "Brand Strategy / UX / Art Direction",
  brief: "用产品化叙事讲清低代码能力，让不同决策角色快速理解价值并进入合适的转化路径。",
  image: "/assets/library/04-projects/03-wanying-site/ai-cover/wanying-cover.webp",
  caseStyle: "website",
  gallery: [
    "/assets/library/04-projects/03-wanying-site/ai-gallery/01-home.webp",
    "/assets/library/04-projects/03-wanying-site/ai-gallery/02-product-center.webp",
    "/assets/library/04-projects/03-wanying-site/ai-gallery/03-visual-builder.webp",
    "/assets/library/04-projects/03-wanying-site/ai-gallery/04-workflow.webp",
    "/assets/library/04-projects/03-wanying-site/ai-gallery/05-data-model.webp",
    "/assets/library/04-projects/03-wanying-site/ai-gallery/06-integration.webp",
    "/assets/library/04-projects/03-wanying-site/ai-gallery/07-solutions.webp",
    "/assets/library/04-projects/03-wanying-site/ai-gallery/08-cases.webp",
    "/assets/library/04-projects/03-wanying-site/ai-gallery/09-pricing.webp",
    "/assets/library/04-projects/03-wanying-site/ai-gallery/10-trial.webp",
  ],
  metrics: [["10", "完整官网页面"], ["6", "决策角色路径"], ["4", "产品能力支柱"]],
  meta: { type: "企业低代码平台官网", role: "品牌策略 / UX / 视觉指导", period: "12 周", status: "完整官网案例", year: "2024" },
  overview: "万应工场官网承载产品认知、行业教育、客户信任与销售转化。设计以低代码平台真实能力为核心，把可视化构建、数据模型、自动化流程与集成中心转译为易理解、可验证的企业产品叙事，并为业务负责人、技术决策者、生态伙伴和开发者建立不同深度的浏览路径。",
  background: "低代码产品能力多、技术链路长，官网容易陷入功能罗列：业务用户看不懂技术价值，技术用户找不到架构与部署依据，销售线索又缺少足够信任证明。项目需要同时解决产品表达、品牌差异与转化效率。",
  pains: [
    { tag: "PAIN 01", title: "能力很多，但用户记不住平台解决什么", desc: "功能点分散在多个模块，缺少从业务结果到产品能力的清晰叙事。" },
    { tag: "PAIN 02", title: "同一套内容难以服务不同决策角色", desc: "业务负责人关注效率，技术负责人关注架构和安全，生态伙伴关注连接与交付。" },
    { tag: "PAIN 03", title: "企业信任与试用转化之间存在断层", desc: "案例、客户、部署与服务保障分散，用户在提交试用前无法连续完成风险判断。" },
  ],
  goal: "建立‘价值—能力—证据—行动’四层叙事，让访客在最短路径内理解产品、找到适用场景、验证企业级可信度，并自然进入演示、咨询或试用。",
  research: [
    { method: "内容盘点", sample: "86 个现有内容模块", finding: "重复功能描述很多，但产品架构、决策依据和客户证据之间缺少连接。" },
    { method: "决策链访谈", sample: "14 位业务与技术角色", finding: "不同角色需要不同信息深度，却共享价值、案例、安全和部署四类关键判断。" },
    { method: "竞品基准", sample: "12 个企业软件官网", finding: "高质量官网用产品实景解释能力，用结构与证据建立专业感，而不是依赖抽象口号。" },
    { method: "转化路径分析", sample: "6 条核心访问路径", finding: "试用前最常回看的内容是客户案例、部署方式、服务保障与产品演示。" },
  ],
  insights: [
    "首屏必须同时回答产品是什么、解决什么、如何运行，并让产品界面成为第一视觉证据。",
    "功能页适合短而聚焦，解决方案与案例页需要更长的行业上下文，页面长度应该服从任务。",
    "企业级品牌感来自信息自信、真实产品细节和可验证证据，而不是装饰密度。",
  ],
  contribution: "负责官网策略、信息架构、页面节奏与视觉系统，定义价值主张和四大能力支柱，规划首页、产品、功能、解决方案、案例、定价与试用 10 个页面，并建立适配长短页面的组件、产品界面展示、立体品牌资产和转化模块规范。",
  contributionTags: ["品牌策略", "内容架构", "官网 UX", "产品叙事", "视觉指导", "转化设计"],
  contributionSplit: [
    { label: "策略与内容架构", value: 30 },
    { label: "页面体验与路径", value: 25 },
    { label: "视觉系统与指导", value: 28 },
    { label: "组件与交付规范", value: 17 },
  ],
  coreDesign: [
    { problem: "产品价值被大量能力点稀释", insight: "用户先理解结果，再理解机制", solution: "以‘让复杂业务快速成为可运行应用’统领首页，再用四大能力支柱解释平台如何实现。", impact: "产品记忆点从功能清单变成完整价值" },
    { problem: "所有页面长度和版式趋同", insight: "页面节奏取决于用户任务", solution: "功能页采用高清聚焦首屏，解决方案与案例页用适度长页完成上下文和证据叙事。", impact: "浏览节奏更自然，重点更清楚" },
    { problem: "抽象科技视觉缺少产品可信度", insight: "真实产品界面就是最有力的品牌资产", solution: "把构建器、工作流、数据关系与集成拓扑放大为主视觉，并用透明模块建立统一识别。", impact: "品牌差异与产品理解同步提升" },
    { problem: "案例、部署和试用彼此割裂", insight: "企业转化是连续的风险确认过程", solution: "在关键页面串联客户结果、部署方式、服务保障与试用入口，形成分层 CTA。", impact: "从认知到咨询的路径连续" },
  ],
  principles: [
    { title: "产品即品牌", desc: "让产品界面和工作机制成为官网最主要的视觉资产。" },
    { title: "长度服从任务", desc: "短页聚焦能力，长页完成行业与证据叙事。" },
    { title: "价值逐层展开", desc: "从结果到能力，再到案例与部署依据。" },
    { title: "每页都有下一步", desc: "让演示、咨询与试用跟随用户决策深度自然出现。" },
  ],
  timeline: [
    { phase: "DISCOVER", title: "内容与决策研究", desc: "盘点现有官网并理解业务、技术和生态角色的判断依据。" },
    { phase: "FRAME", title: "叙事与站点地图", desc: "建立四层内容模型和十个页面的角色路径。" },
    { phase: "DESIGN", title: "页面与品牌系统", desc: "完成不同长度页面、产品 UI 展示和立体品牌资产。" },
    { phase: "DELIVER", title: "响应式与转化规范", desc: "统一组件、页面节奏、CTA 与内容交付规则。" },
  ],
  stack: ["Figma", "Content Strategy", "Information Architecture", "Design Tokens", "Prototype", "Responsive Web"],
  capabilities: [
    { label: "品牌策略", value: 94 }, { label: "内容架构", value: 95 }, { label: "官网体验", value: 93 }, { label: "视觉指导", value: 94 }, { label: "转化设计", value: 90 },
  ],
  outcome: "完成 10 个各自承担明确任务的官网页面：功能页保持高清聚焦，首页、解决方案和案例页保留完整叙事；整套体验以同一品牌、栅格、产品 UI 与转化组件贯穿，既能解释低代码能力，也能支撑企业客户的信任与决策。",
  outcomeBars: [
    { label: "核心页面覆盖", value: 100, caption: "10 个页面" },
    { label: "决策角色路径", value: 92, caption: "6 类角色" },
    { label: "产品能力表达", value: 94, caption: "4 大支柱" },
    { label: "转化节点连续", value: 90, caption: "演示 / 咨询 / 试用" },
  ],
  details: [["背景", "低代码产品能力复杂，官网同时承担产品教育、企业信任与销售转化。"], ["方法", "以价值、能力、证据和行动组织信息，并按任务决定页面长度。"], ["结果", "形成 10 个完整页面和一套统一、清晰且具有产品识别度的官网系统。"]],
};

const legacyProjects = [
  {
    id: "wanying",
    code: "WANYING",
    type: "ENTERPRISE LOW-CODE PLATFORM",
    title: "万应低代码平台设计系统",
    role: "Design System Lead / UI Design Lead",
    brief: "从 0 到 1 构建变量、组件、可视化编辑器、后台管理与治理流程。",
    image: "/assets/library/04-projects/01-wanying/cover/wanying.webp",
    gallery: [
      "/assets/library/04-projects/01-wanying/gallery/设计变量-dark.webp",
      "/assets/library/04-projects/01-wanying/gallery/Table表格.webp",
      "/assets/library/04-projects/01-wanying/gallery/新增快速构建.webp",
      "/assets/library/04-projects/01-wanying/gallery/新版首页.webp",
      "/assets/library/04-projects/01-wanying/gallery/34e9d0d9-196c-4909-9559-1f01ba8fdd67.webp",
    ],
    metrics: [["40+", "核心组件"], ["6", "系统模块"], ["30%", "重复设计减少"]],
    meta: { type: "企业级低代码平台", role: "设计系统主理 / UI 设计负责人", period: "2 年", status: "已上线 / 持续演进", year: "2021—2023" },
    overview: "一套支撑多业务线并行交付的低代码平台设计系统，覆盖变量、组件、可视化编辑器、管理后台与治理流程。",
    pains: [
      { tag: "PAIN 01", title: "标准分散", desc: "多业务线并行，界面风格不统一，每次新功能都在重复造轮子。" },
      { tag: "PAIN 02", title: "还原成本高", desc: "设计稿与代码命名脱节，研发反复确认才能落地，迭代缓慢。" },
      { tag: "PAIN 03", title: "组件被当资产", desc: "组件只存图，没有状态、边界与验收标准，无法真正复用。" },
    ],
    goal: "用一套统一的设计语言串起产品、设计与研发，让同一套命名既能描述界面，也能映射代码。",
    contribution: "独立负责设计系统整体规划与落地，完成 Token 体系、组件库、可视化编辑器与管理后台体验，并推动评审、命名与归档机制进入团队日常交付流程，方案最终落地为可持续演进的产品语言。",
    contributionTags: ["系统规划", "Token 体系", "组件库", "可视化编辑器", "管理后台", "设计治理"],
    contributionSplit: [
      { label: "系统规划与 Token", value: 22 },
      { label: "组件库设计", value: 30 },
      { label: "可视化编辑器", value: 24 },
      { label: "管理后台与治理", value: 24 },
    ],
    coreDesign: [
      { problem: "标准分散导致重复沟通", insight: "Token 是设计与代码的共同语言", solution: "按业务层级、组件状态与研发映射组织变量，让设计与代码用同一套命名描述界面。", impact: "重复沟通显著减少" },
      { problem: "组件只被当作视觉资产", insight: "组件是产品语言而非图片库", solution: "把组件沉淀为含使用场景、边界规则、交互状态与研发验收标准的可复用单元。", impact: "复用率提升" },
      { problem: "低代码能力难被普通用户理解", insight: "复杂配置要拆成肌肉记忆", solution: "重点处理拖拽吸附、属性同步、状态预览与发布，把复杂操作压成可学习路径。", impact: "上手门槛降低" },
    ],
    timeline: [
      { phase: "PHASE 01", title: "Token 体系", desc: "建立颜色 / 字体 / 间距 / 状态变量" },
      { phase: "PHASE 02", title: "组件库", desc: "沉淀 40+ 核心组件与状态规范" },
      { phase: "PHASE 03", title: "可视化编辑器", desc: "拖拽吸附 / 属性同步 / 发布" },
      { phase: "PHASE 04", title: "治理流程", desc: "评审 / 命名 / 归档进入日常交付" },
    ],
    stack: ["Figma", "Design Tokens", "React", "低代码引擎", "组件库"],
    capabilities: [
      { label: "系统思维", value: 95 },
      { label: "组件抽象", value: 90 },
      { label: "交互设计", value: 82 },
      { label: "视觉表达", value: 80 },
      { label: "研发协同", value: 88 },
    ],
    outcome: "完成从 Token、组件到编辑器与治理的完整闭环，沉淀 40+ 核心组件与 6 个系统模块，让设计系统成为持续演进的组织能力。",
    outcomeBars: [
      { label: "核心组件沉淀", value: 92, caption: "40+ 组件" },
      { label: "系统模块覆盖", value: 80, caption: "6 大模块" },
      { label: "重复设计减少", value: 70, caption: "约 30%" },
      { label: "研发协同效率", value: 85, caption: "命名对齐" },
    ],
    details: [
      ["背景", "多业务线并行开发，界面标准分散，设计还原与迭代成本持续升高。"],
      ["方法", "从 Token 切入，沉淀组件与核心交互，再建立评审、命名与归档机制。"],
      ["结果", "让设计系统从一次性交付变成持续演进、可被研发复用的组织能力。"],
    ],
  },
  {
    id: "admin",
    code: "ADMIN",
    type: "ENTERPRISE ADMIN CONSOLE",
    title: "企业级权限与流程管理平台",
    role: "Lead UI Designer",
    brief: "重构权限、组织架构、审批流程与数据表格体验。",
    image: "/assets/library/04-projects/02-admin/cover/admin.webp",
    gallery: [
      "/assets/library/04-projects/02-admin/gallery/工作台.webp",
      "/assets/library/04-projects/02-admin/gallery/业务逻辑.webp",
      "/assets/library/04-projects/02-admin/gallery/数据模型设计器.webp",
      "/assets/library/04-projects/02-admin/gallery/素材管理-图片-网格.webp",
      "/assets/library/04-projects/02-admin/gallery/运维监控.webp",
    ],
    metrics: [["12", "权限场景"], ["28", "页面模板"], ["22%", "路径缩短"]],
    meta: { type: "企业管理平台", role: "UI 设计主负责人", period: "6 个月", status: "已上线", year: "2023" },
    overview: "面向企业内部权限、组织架构、审批流程与数据表格体验的管理平台重构，把复杂管理任务拆成清晰、稳定、可学习的操作路径。",
    pains: [
      { tag: "PAIN 01", title: "权限交叉", desc: "角色与数据权限纠缠，用户常不清楚自己能做什么、为何被禁用。" },
      { tag: "PAIN 02", title: "信息层级松散", desc: "后台域多、入口分散，新老用户都容易在任务中迷路。" },
      { tag: "PAIN 03", title: "表格密度过高", desc: "高频操作埋在深层菜单，筛选与批量体验割裂。" },
    ],
    goal: "重组信息架构与角色路径，让管理动作有稳定、可预期的操作回路。",
    contribution: "独立负责管理后台的信息架构、权限矩阵、表格模式与异常状态设计，完成 28 个页面模板与 12 类权限场景的梳理与视觉落地，并主导与研发的验收对齐。",
    contributionTags: ["信息架构", "权限矩阵", "表格体系", "异常状态", "页面模板", "研发验收"],
    contributionSplit: [
      { label: "信息架构与权限", value: 30 },
      { label: "表格与表单体系", value: 28 },
      { label: "异常与状态设计", value: 22 },
      { label: "页面模板与验收", value: 20 },
    ],
    coreDesign: [
      { problem: "权限交叉导致误操作", insight: "权限要可见可解释", solution: "建立统一的权限矩阵与状态可视化，让用户始终清楚能做什么、为什么不能做。", impact: "误操作下降" },
      { problem: "表格密度高、操作路径深", insight: "高频动作压到两步以内", solution: "统一表格模式（筛选 / 批量 / 内联编辑 / 异常反馈），把高频操作压到两步以内。", impact: "路径缩短 22%" },
      { problem: "管理任务缺少可预期性", insight: "复杂任务要变成肌肉记忆", solution: "通过树状导航与稳定的状态流转，让复杂任务成为可被学习的操作路径。", impact: "学习成本降低" },
    ],
    timeline: [
      { phase: "PHASE 01", title: "信息架构", desc: "梳理后台域与角色路径" },
      { phase: "PHASE 02", title: "权限矩阵", desc: "统一 12 类权限场景与状态" },
      { phase: "PHASE 03", title: "表格体系", desc: "28 个页面模板与批量模式" },
      { phase: "PHASE 04", title: "异常与验收", desc: "异常反馈与研发对齐落地" },
    ],
    stack: ["Figma", "Axure", "React", "Ant Design", "ECharts"],
    capabilities: [
      { label: "信息架构", value: 92 },
      { label: "复杂表格", value: 90 },
      { label: "权限建模", value: 85 },
      { label: "异常设计", value: 82 },
      { label: "研发协同", value: 80 },
    ],
    outcome: "完成 12 类权限场景与 28 个页面模板的统一，关键路径缩短约 22%，让复杂管理任务变成稳定可学习的操作路径，平台已上线交付。",
    outcomeBars: [
      { label: "权限场景覆盖", value: 88, caption: "12 类场景" },
      { label: "页面模板沉淀", value: 82, caption: "28 个模板" },
      { label: "关键路径缩短", value: 65, caption: "约 22%" },
      { label: "操作可学习性", value: 86, caption: "稳定回路" },
    ],
    details: [
      ["背景", "后台域多、权限交叉、信息层级松散，新老用户都容易在任务中迷路。"],
      ["方法", "重组信息架构与角色路径，统一权限矩阵、表格模式和异常状态。"],
      ["结果", "复杂管理任务被拆成清晰、稳定、可学习的操作路径。"],
    ],
  },
  {
    id: "mobile",
    code: "MOBILE",
    type: "MOBILE PRODUCT / MINI PROGRAM",
    title: "移动端服务小程序体验升级",
    role: "Product Interface Designer",
    brief: "围绕查询、任务、消息与转化，重构移动端核心路径。",
    image: "/assets/library/04-projects/03-mobile/cover/mobile.webp",
    gallery: [
      "/assets/library/04-projects/03-mobile/gallery/mobile.webp",
      "/assets/library/04-projects/03-mobile/gallery/浅色外观-移动端.webp",
      "/assets/library/04-projects/03-mobile/gallery/变量.webp",
      "/assets/library/04-projects/03-mobile/gallery/新增快速构建.webp",
    ],
    metrics: [["3", "核心人群"], ["18%", "入口点击提升"], ["2.4×", "路径更清晰"]],
    meta: { type: "移动端 / 小程序", role: "产品界面设计", period: "4 周", status: "已上线", year: "2024" },
    overview: "围绕查询、任务、消息与转化，重构移动端核心路径的服务小程序体验升级，让关键功能触达更短、回访更连贯。",
    pains: [
      { tag: "PAIN 01", title: "入口多层级深", desc: "功能散落在多级菜单，关键动作被埋没，转化被打断。" },
      { tag: "PAIN 02", title: "消息与任务割裂", desc: "通知与待办分属不同模块，回访后难以回到原有上下文。" },
      { tag: "PAIN 03", title: "人群差异大", desc: "新用户、老用户、运维人员路径需求不同，单一首页难以兼顾。" },
    ],
    goal: "以用户旅程为起点重排首页层级，让回访后能更快回到原有任务上下文。",
    contribution: "独立负责移动端核心路径的梳理与界面设计，围绕 3 类核心人群完成首页层级重排、任务入口统一与消息中心重构，并主导高保真原型与研发对接。",
    contributionTags: ["用户旅程", "信息架构", "首页重排", "任务入口", "消息中心", "高保真原型"],
    contributionSplit: [
      { label: "用户旅程与人群", value: 26 },
      { label: "首页层级重排", value: 30 },
      { label: "任务与消息统一", value: 24 },
      { label: "原型与研发对接", value: 20 },
    ],
    coreDesign: [
      { problem: "入口多层级深导致转化打断", insight: "关键动作回到首屏一步可达", solution: "以 3 类核心人群为起点重排首页层级，让关键动作回到首屏一步可达。", impact: "入口点击 +18%" },
      { problem: "消息与任务割裂", insight: "回访要能续接上下文", solution: "统一任务入口与消息中心，回访后直接回到原有任务上下文。", impact: "回访更连贯" },
      { problem: "回访路径不连贯", insight: "保留状态记忆", solution: "保留任务上下文与状态记忆，让再次进入像继续一段未完成的动作。", impact: "路径清晰度 ×2.4" },
    ],
    timeline: [
      { phase: "PHASE 01", title: "用户旅程", desc: "梳理 3 类核心人群与任务路径" },
      { phase: "PHASE 02", title: "首页重排", desc: "层级压缩 / 关键动作首屏化" },
      { phase: "PHASE 03", title: "任务与消息", desc: "统一入口与上下文续接" },
      { phase: "PHASE 04", title: "原型与对接", desc: "高保真原型与研发落地" },
    ],
    stack: ["Figma", "微信小程序", "Principle", "Rematch"],
    capabilities: [
      { label: "用户旅程", value: 90 },
      { label: "信息架构", value: 88 },
      { label: "移动交互", value: 92 },
      { label: "视觉表达", value: 78 },
      { label: "原型验证", value: 85 },
    ],
    outcome: "完成 3 类核心人群的路径重构，入口点击提升约 18%，路径清晰度提升 2.4 倍，关键功能触达更短并支持回访续接，小程序已上线。",
    outcomeBars: [
      { label: "入口点击提升", value: 72, caption: "约 18%" },
      { label: "路径清晰度", value: 90, caption: "×2.4" },
      { label: "人群路径覆盖", value: 78, caption: "3 类人群" },
      { label: "回访续接率", value: 84, caption: "上下文保留" },
    ],
    details: [
      ["背景", "功能入口多、层级深，消息与任务割裂，关键转化路径被打断。"],
      ["方法", "以用户旅程和 3 类核心人群为起点，重排首页层级并统一任务入口。"],
      ["结果", "关键功能触达更短，回访后能更快回到原有任务上下文。"],
    ],
  },
];

export const projects = [cdezProject, mysteryProject, wanyingSiteProject];

export const works = [
  { src: "/assets/library/05-graphic/三星堆海报.jpg", title: "三星堆", type: "POSTER / CULTURE" },
  { src: "/assets/library/05-graphic/湘遇好礼海报.jpg", title: "湘遇好礼", type: "BRAND / CAMPAIGN" },
  { src: "/assets/library/05-graphic/佛像海报.jpg", title: "造像", type: "POSTER / CULTURE" },
  { src: "/assets/library/05-graphic/个人工作站loading页.jpg", title: "个人工作站", type: "MOTION / LOADING" },
  { src: "/assets/library/05-graphic/Frame 1041253.webp", title: "视觉试验", type: "GRAPHIC / EDITORIAL" },
  { src: "/assets/library/05-graphic/image 134.jpg", title: "图形档案", type: "GRAPHIC / SYSTEM" },
  { src: "/assets/library/05-graphic/Frame 1041254.webp", title: "版式练习", type: "EDITORIAL / TYPE" },
  { src: "/assets/library/05-graphic/Group 1321316532.webp", title: "视觉切片 01", type: "GRAPHIC / ARCHIVE" },
  { src: "/assets/library/05-graphic/Group 1321316534.webp", title: "视觉切片 02", type: "GRAPHIC / ARCHIVE" },
  { src: "/assets/library/05-graphic/Group 1321316535.webp", title: "视觉切片 03", type: "GRAPHIC / ARCHIVE" },
  { src: "/assets/library/05-graphic/Group 1321316536.webp", title: "视觉切片 04", type: "GRAPHIC / ARCHIVE" },
  { src: "/assets/library/05-graphic/Group 1321316537.webp", title: "视觉切片 05", type: "GRAPHIC / ARCHIVE" },
  { src: "/assets/library/05-graphic/image 118.jpg", title: "影像实验", type: "IMAGE / STUDY" },
  { src: "/assets/library/05-graphic/image 138.jpg", title: "材质档案", type: "IMAGE / STUDY" },
  { src: "/assets/library/05-graphic/RAW.jpg", title: "RAW", type: "IMAGE / STUDY" },
  { src: "/assets/library/05-graphic/器与留白.jpg", title: "器与留白", type: "GRAPHIC / EDITORIAL" },
  { src: "/assets/library/05-graphic/山止乌龙茶.jpg", title: "山止乌龙茶", type: "BRAND / PACKAGE" },
  { src: "/assets/library/05-graphic/山海新声.jpg", title: "山海新声", type: "POSTER / CULTURE" },
  { src: "/assets/library/05-graphic/挪威冰岛.jpg", title: "挪威冰岛", type: "IMAGE / TRAVEL" },
  { src: "/assets/library/05-graphic/潮汐现场.jpg", title: "潮汐现场", type: "GRAPHIC / ARCHIVE" },
  { src: "/assets/library/05-graphic/燃劫此刻.jpg", title: "燃劫此刻", type: "POSTER / CULTURE" },
  { src: "/assets/library/05-graphic/生长.jpg", title: "生长", type: "GRAPHIC / SYSTEM" },
  { src: "/assets/library/05-graphic/长沙海报.jpg", title: "长沙", type: "POSTER / CITY" },
];

export const vibeProjects = [
  {
    index: "01", code: "X-GZ", title: "小小馆长", subtitle: "成长记录 / 藏品策展 / 睡眠故事",
    tags: "WECHAT MINI-PROGRAM · AI · FAMILY", image: "/assets/library/06-vibe/01-xiaoxiaoguanzhang/audio-lab.webp", mediaType: "image",
    wechat: { qr: "/assets/library/06-vibe/01-xiaoxiaoguanzhang/qrcode.webp", hint: "微信搜索「小小馆长」立即体验" },
    description: "把孩子喜欢的东西变成博物馆藏品，基于藏品生成专属睡眠故事，支持童言、第一次、日志与策展记录。",
    background: "传统成长记录靠相册与日记，素材零散、缺少故事性，孩子的好奇心与童言随时间遗忘，无法被结构化保存与回看。",
    problem: "成长记录碎片化：照片散落相册，童言与第一次靠记忆，缺少把孩子视角的收藏转化为可回看、可策展叙事的工具。",
    solution: "以藏品为核心，记录童言、第一次与日常日志，AI 基于藏品生成专属睡眠故事，支持 3D 化藏品与访问朋友博物馆。",
    stack: ["微信小程序", "Three.js", "LLM API", "云开发"],
    highlights: ["藏品化记录孩子喜好", "基于藏品生成专属睡眠故事", "童言 / 第一次 / 日志结构化沉淀", "3D 藏品与跨朋友博物馆互访"],
    link: "#",
  },
  {
    index: "02", code: "V-ALC", title: "声纹炼金炉", subtitle: "人声训练 / 声纹替换 / 母带翻唱",
    tags: "WEB AUDIO · AI VOICE · ENTERTAINMENT", image: "/assets/library/06-vibe/02-travel-archive/travel-archive.webp", mediaType: "image",
    description: "PC 端网页娱乐工具，训练个人人声模型，对歌曲提取人声、声纹替换并后期母带，生成翻唱作品。",
    background: "想用自己的声音翻唱喜欢的歌，但传统流程要在宿主软件里手动对轨、调效果器，还需要本地部署 AI 模型，门槛高且碎片化。",
    problem: "翻唱链路割裂：人声提取、声纹训练、替换、母带各用不同工具，参数无法互通，普通用户难以独立完成一首翻唱。",
    solution: "在浏览器内串联人声训练→歌曲分离→声纹替换→母带后期→导出全流程，每步参数保留可回溯，降低翻唱门槛。",
    stack: ["React", "Web Audio API", "Python AI", "FFmpeg.wasm"],
    highlights: ["录制并训练个人人声模型", "一键分离歌曲人声与伴奏", "声纹替换实时预览对比", "母带后期与多版本导出"],
    link: "#",
  },
  {
    index: "03", code: "M-HANG", title: "墨航 · 文学实验室", subtitle: "小说创作 / AI 自动写作 / 本地优先",
    tags: "AI · LITERATURE · FULL-STACK", image: "/assets/library/06-vibe/03-pixel-alchemy/pixel-alchemy.webp", mediaType: "image",
    description: "面向创作者的小说创作工作台，整合项目管理、创作中心、PRD 文档与 AI 自动写作，本地优先、数据自持。",
    background: "写作者在使用通用文档工具时，创作素材、大纲、设定、章节散落各处，AI 辅助写作只能片段生成，无法贯穿整本小说的设定与连续性。",
    problem: "创作工具割裂：项目管理、正文写作、设定维护与 AI 生成各用一套，设定无法跨章节复用，AI 不理解既有世界观，长篇连贯性难维护。",
    solution: "以工作台为核心，整合小说项目、创作中心、PRD 文档与设置，AI Agent 基于本地设定自动续写，保证世界观一致与创作链路完整。",
    stack: ["React", "Node.js", "SQLite", "LLM API"],
    highlights: ["工作台统一管理多本小说项目", "创作中心与设定文档联动", "AI Agent 基于本地设定自动续写", "本地优先，数据自持可离线"],
    link: "https://mohang.zenslab.top",
  },
  {
    index: "04", code: "S-LJ", title: "食旅集", subtitle: "菜单识别 / 可视化点单 / 跨语言点餐",
    tags: "AI · TRAVEL · FULL-STACK", image: "/assets/library/06-vibe/04-shilvji/image-bureau.webp", mediaType: "image",
    description: "拍下外文菜单，AI 识别分类、匹配图片、换算价格，生成可视化中文点单界面。",
    background: "去国外旅行吃饭时，菜单全是外文，菜名看不懂、价格要换算、不知道长什么样，只能靠猜或随便指，点餐体验紧张又低效。",
    problem: "语言障碍 + 信息缺失：外文菜名无法理解，缺少菜品图片参考，价格需心算换算，点完无法确认，与服务员沟通成本高。",
    solution: "拍下菜单 → AI 识别菜品并分类 → 自动搜索对应图片 → 生成带中文名、换算价格的可视化菜单 → 勾选提交小票单，全程不靠口语沟通。",
    stack: ["React", "Node.js", "OCR / Vision API", "Tailwind"],
    highlights: ["菜单拍照即识别分类", "自动匹配菜品参考图", "中文名称与汇率换算价格", "点单小票一键提交服务员"],
    link: "https://slj.zenslab.top",
  },
];
