export const chapters = [
  { id: "about", label: "ABOUT", zh: "个人概览" },
  { id: "experience", label: "EXPERIENCE", zh: "职业经历" },
  { id: "wanying", label: "WANYING", zh: "万应低代码" },
  { id: "projects", label: "PROJECTS", zh: "代表项目" },
  { id: "graphic", label: "VISUAL", zh: "视觉设计" },
  { id: "vibe", label: "AI × DESIGN", zh: "AI 创作" },
];

export const profile = {
  heroName: "ZEN.TANG",
  heroRole: "Product Designer · Designer & Builder",
  heroLine: "10+ 年产品体验设计师，从产品构想、设计系统到可运行产品，把设计判断推进到真正落地。",
  heroTags: ["Product Design", "Design System", "AI × Builder"],
  cta: "VIEW FULL PROFILE / 查看完整档案",
  stats: [
    ["10+", "年产品体验与设计实践"],
    ["0→1", "从构想到可运行产品落地"],
    ["MULTI", "B 端 · AI · 移动端 · 数据可视化"],
  ],
  info: [
    ["姓名", "唐启东"],
    ["所在地", "长沙 / 中国"],
    ["职业", "Product Designer"],
    ["经验", "10+ Years"],
    ["方向", "B 端 · AI · 移动端 · 数据可视化"],
    ["邮箱", "zen92@foxmail.com"],
  ],
  philosophy: {
    lead: "多数设计师的边界停在原型与交付，我的边界是：产品构想 → 结构与流程 → 视觉系统 → AI 与代码实现 → 可运行产品。",
    pillars: [
      { icon: "ux", title: "用户体验", en: "UX", desc: "从真实场景出发，解决复杂产品问题，而非只做视觉表达。" },
      { icon: "product", title: "产品思维", en: "Product", desc: "关注业务目标与用户任务，让设计服务于产品而非停在界面。" },
      { icon: "tech", title: "技术落地", en: "Build", desc: "通过 AI 与代码，把设计推进到可运行、可验证的产品。" },
    ],
  },
  capabilities: [
    { icon: "product", group: "Product Design", items: ["用户体验设计", "信息架构", "产品流程设计", "复杂系统设计"] },
    { icon: "visual", group: "Visual Design", items: ["品牌视觉", "KV 设计", "3D 视觉", "插画设计"] },
    { icon: "ai", group: "AI Product", items: ["AI 产品设计", "Prompt Engineering", "AI 工作流", "Vibe Coding"] },
    { icon: "system", group: "System Design", items: ["Design System", "Component Library", "Design Token"] },
  ],
  timeline: [
    ["2015", "进入 UI 设计领域", "建立视觉与界面基础"],
    ["2018", "深入企业级产品", "从视觉执行走向业务与信息架构"],
    ["2021", "负责复杂 B 端系统与数据平台", "主导设计系统建设"],
    ["2024", "探索 AI 产品与智能化流程", "从设计稿走向 AI 与代码实现"],
    ["2026", "独立构建可运行产品", "产品构想 → 设计 → 落地的完整闭环"],
  ],
  workflow: ["Research", "Define", "Design", "Prototype", "Code", "Validate"],
  workflowDesc: "多数 UI 的边界停在原型 → 设计稿 → 开发交付。我把它推进到：产品构想 → 结构与流程 → 视觉系统 → AI 与代码实现 → 可运行产品。",
  stack: [
    { group: "Design", items: ["Figma", "Adobe", "C4D"] },
    { group: "AI", items: ["ChatGPT", "Claude", "Midjourney", "ComfyUI"] },
    { group: "Development", items: ["React", "Three.js", "TypeScript", "Tailwind"] },
  ],
  beyond: [
    { icon: "travel", title: "Travel", desc: "探索不同文化与视觉语言" },
    { icon: "music", title: "Music", desc: "AI 音乐实验与声音设计" },
    { icon: "photo", title: "Photography", desc: "记录城市与自然瞬间" },
    { icon: "rocket", title: "AI Exploration", desc: "持续探索新工具和创造方式" },
  ],
  signature: "Designer × Builder",
};

export const career = [
  {
    version: "V1.0",
    role: "UI Designer",
    period: "2015—2017",
    note: "从视觉表达进入数字产品，建立界面与品牌基础。",
    stage: "FOUNDATION",
    en: "Visual Foundation",
    keyword: "视觉",
    overview: "从视觉设计切入数字产品，建立对界面层级、排版节奏与品牌一致性的基础认知，把抽象的视觉判断转化为可复用的界面语言。",
    focus: ["视觉表达", "界面排版", "品牌延展", "基础交互"],
    deliveries: ["基础色彩 / 字体 / 栅格规范", "Web 与移动端界面视觉交付", "品牌视觉延展至运营物料"],
    lesson: "学会用视觉解决「看起来对」的问题，但开始意识到界面背后还有更深的逻辑。",
    shift: "从「画好看的界面」走向「理解界面背后的逻辑」",
  },
  {
    version: "V2.0",
    role: "Product Interface Designer",
    period: "2018—2020",
    note: "深入业务流程，把复杂需求转译成清晰界面。",
    stage: "BUSINESS",
    en: "Product Thinking",
    keyword: "业务",
    overview: "从视觉执行深入业务流程，把复杂需求拆解成清晰的信息架构与任务路径，让界面真正服务于用户目标而非只是好看。",
    focus: ["业务理解", "信息架构", "任务流程", "可用性"],
    deliveries: ["多业务域导航与角色路径梳理", "复杂审批与表单流程化", "基于任务场景的可用性优化"],
    lesson: "界面是结果，业务与任务才是起点；先定义问题，再定义界面。",
    shift: "从「画界面」走向「定义问题与任务路径」",
  },
  {
    version: "V3.0",
    role: "Design System Builder",
    period: "2021—2023",
    note: "用组件、变量和规范支撑多业务线协作。",
    stage: "SYSTEM",
    en: "System Building",
    keyword: "系统",
    overview: "从单个项目上升到系统层面，用 Token、组件与规范支撑多业务线并行交付，让设计从一次性产物变成可被研发复用的组织能力。",
    focus: ["系统抽象", "组件体系", "研发协同", "治理流程"],
    deliveries: ["Token 体系：颜色 / 字体 / 间距 / 状态", "40+ 组件库与状态规范", "评审 / 命名 / 归档治理流程"],
    lesson: "设计系统的价值不在组件数量，而在它能否被研发真正复用并持续演进。",
    shift: "从「做项目」走向「建系统」",
  },
  {
    version: "V4.0",
    role: "Designer & Builder",
    period: "2024—NOW",
    note: "从设计稿走向 AI 与代码，独立构建可运行产品。",
    stage: "BUILDER",
    en: "Product Builder",
    keyword: "落地",
    overview: "不再停在原型与交付，而是从产品构想出发，用 AI 与代码把设计判断推进到可运行、可验证的产品，打通产品 → 设计 → 落地的完整闭环。",
    focus: ["AI 产品设计", "Vibe Coding", "可运行产品", "设计到落地"],
    deliveries: ["从构想到可运行产品的独立构建", "AI 驱动的设计与开发流程", "产品 / 设计 / 代码的完整闭环"],
    lesson: "设计的终点不是交付稿，而是让正确的产品判断真正跑起来。",
    shift: "从「交付设计稿」走向「交付可运行产品」",
  },
];

export const systemModules = [
  {
    id: "tokens",
    index: "01",
    title: "Design Tokens / 设计令牌",
    tabLabel: "设计令牌",
    tabEn: "Design Tokens",
    caption: "Color / Type / Space / State",
    description: "颜色、字体、间距、状态变量，让设计与代码用同一套命名描述界面。",
    detail: "变量按业务层级与研发映射组织，减少重复沟通。",
    tags: ["Color Tokens", "Typography", "Spacing", "State Map"],
    image: "/assets/library/03-wanying/01-tokens/设计变量-dark.png",
    gallery: [
      "/assets/library/03-wanying/01-tokens/设计变量-dark.png",
      "/assets/library/03-wanying/01-tokens/设计变量-light.png",
      "/assets/library/03-wanying/01-tokens/基础颜色.png",
      "/assets/library/03-wanying/01-tokens/字体.png",
      "/assets/library/03-wanying/01-tokens/边框.png",
      "/assets/library/03-wanying/01-tokens/阴影.png",
      "/assets/library/03-wanying/01-tokens/设计原则.png",
      "/assets/library/03-wanying/01-tokens/ScreenShot_2026-06-20_125309_829.png",
      "/assets/library/03-wanying/01-tokens/ScreenShot_2026-06-20_125338_843.png",
    ],
  },
  {
    id: "components",
    index: "02",
    title: "Component Library / 组件库",
    tabLabel: "组件库",
    tabEn: "Components",
    caption: "Button / Table / Modal / Workflow",
    description: "覆盖后台、表单、流程、图表与低代码画布的组件库，含状态与边界规范。",
    detail: "组件是含使用场景、交互状态与验收标准的可复用产品语言。",
    tags: ["Default", "Hover", "Active", "Disabled", "Loading"],
    image: "/assets/library/03-wanying/02-components/Table表格.png",
    gallery: [
      "/assets/library/03-wanying/02-components/Button 按钮.png",
      "/assets/library/03-wanying/02-components/Input  输入框.png",
      "/assets/library/03-wanying/02-components/Select  选择器.png",
      "/assets/library/03-wanying/02-components/Table表格.png",
      "/assets/library/03-wanying/02-components/Form 表单.png",
      "/assets/library/03-wanying/02-components/Checkbox  多选.png",
      "/assets/library/03-wanying/02-components/Radio 单选.png",
      "/assets/library/03-wanying/02-components/Switch 开关.png",
      "/assets/library/03-wanying/02-components/Tabs 标签页.png",
      "/assets/library/03-wanying/02-components/Tag  标签.png",
      "/assets/library/03-wanying/02-components/Dropdown 下拉菜单.png",
      "/assets/library/03-wanying/02-components/Pagination 分页.png",
      "/assets/library/03-wanying/02-components/Steps 步骤条.png",
      "/assets/library/03-wanying/02-components/Progress 进度条.png",
      "/assets/library/03-wanying/02-components/Upload 上传.png",
      "/assets/library/03-wanying/02-components/Avatar 头像.png",
      "/assets/library/03-wanying/02-components/Breadcrumb 面包屑.png",
      "/assets/library/03-wanying/02-components/PageHeader 页头.png",
      "/assets/library/03-wanying/02-components/Image 图片.png",
      "/assets/library/03-wanying/02-components/Divider分割线.png",
      "/assets/library/03-wanying/02-components/TimePicker 时间选择器.png",
      "/assets/library/03-wanying/02-components/日期选择器 DatePicker.png",
      "/assets/library/03-wanying/02-components/导航.png",
    ],
  },
  {
    id: "editor",
    index: "03",
    title: "Visual Editor / 可视化编辑器",
    tabLabel: "可视化编辑器",
    tabEn: "Visual Editor",
    caption: "Material / Canvas / Inspector",
    description: "物料、画布、属性面板、工具栏与图层结构的可视化编辑器体验。",
    detail: "拖拽吸附、属性同步、状态预览与发布，让低代码被普通用户理解。",
    tags: ["Drag", "Snap", "Preview", "Publish"],
    image: "/assets/library/03-wanying/03-editor/新增快速构建.png",
    gallery: [
      "/assets/library/03-wanying/03-editor/新增快速构建.png",
      "/assets/library/03-wanying/03-editor/动作设计器.jpg",
      "/assets/library/03-wanying/03-editor/数据流.jpg",
      "/assets/library/03-wanying/03-editor/新增SQL语句.jpg",
      "/assets/library/03-wanying/03-editor/SQL查询语句.png",
      "/assets/library/03-wanying/03-editor/变量.png",
      "/assets/library/03-wanying/03-editor/表格.png",
      "/assets/library/03-wanying/03-editor/运算符.png",
      "/assets/library/03-wanying/03-editor/更新日志.png",
      "/assets/library/03-wanying/03-editor/浅色外观-移动端.png",
    ],
  },
  {
    id: "admin",
    index: "04",
    title: "Admin Console / 管理后台",
    tabLabel: "管理后台",
    tabEn: "Admin Console",
    caption: "Application / Role / Workflow",
    description: "应用管理、角色权限、数据源、流程与日志的后台信息架构。",
    detail: "树状导航与表格批量操作，把复杂任务拆成可学习路径。",
    tags: ["Permission", "Data Source", "Publish", "Log"],
    image: "/assets/library/03-wanying/04-admin/工作台.png",
    gallery: [
      "/assets/library/03-wanying/04-admin/工作台.png",
      "/assets/library/03-wanying/04-admin/新版首页.png",
      "/assets/library/03-wanying/04-admin/业务逻辑.png",
      "/assets/library/03-wanying/04-admin/产品类型.png",
      "/assets/library/03-wanying/04-admin/数据模型设计器.png",
      "/assets/library/03-wanying/04-admin/界面开发.png",
      "/assets/library/03-wanying/04-admin/素材管理-图标-网格.png",
      "/assets/library/03-wanying/04-admin/素材管理-图片-网格.png",
      "/assets/library/03-wanying/04-admin/运维监控.png",
      "/assets/library/03-wanying/04-admin/高级.png",
      "/assets/library/03-wanying/04-admin/AI Agent.png",
    ],
  },
  {
    id: "governance",
    index: "05",
    title: "Governance / 设计治理",
    tabLabel: "设计治理",
    tabEn: "Governance",
    caption: "Review / Handoff / QA / Archive",
    description: "规范维护、命名、评审流程、研发对接与设计验收标准。",
    detail: "确保并行交付时保持一致，让系统持续演进。",
    tags: ["Review", "Handoff", "Design QA", "Versioning"],
    image: "/assets/library/03-wanying/05-governance/governance-new.png",
    gallery: [
      "/assets/library/03-wanying/05-governance/governance-new.png",
      "/assets/library/03-wanying/05-governance/0bb6a7e9-3e93-458c-88b6-26dbb557ea6d.png",
      "/assets/library/03-wanying/05-governance/1a9151d6-079f-471a-bafd-de0f2418a71a.png",
      "/assets/library/03-wanying/05-governance/2cec7238-96de-4de3-9752-9ead7f2f4639.png",
      "/assets/library/03-wanying/05-governance/34e9d0d9-196c-4909-9559-1f01ba8fdd67.png",
      "/assets/library/03-wanying/05-governance/4ed4e5cb-6e0f-4d0f-88f4-4fcaea9e6193.png",
      "/assets/library/03-wanying/05-governance/781d01eb-9d9c-40f2-992d-d3585db0cc9e.png",
      "/assets/library/03-wanying/05-governance/a42ad8a3-c67b-4cd2-8f39-5566b4c06b67.png",
      "/assets/library/03-wanying/05-governance/e8ca16a3-2c65-42b1-a80f-a19a79cb94a3.png",
      "/assets/library/03-wanying/05-governance/ef461c05-f49e-4ef7-ba7d-fd3ea9eb7722.png",
      "/assets/library/03-wanying/05-governance/fcb96bd6-678a-4471-ad65-46fea630565d.png",
    ],
  },
];

export const projects = [
  {
    id: "wanying",
    code: "WANYING",
    type: "ENTERPRISE LOW-CODE PLATFORM",
    title: "万应低代码平台设计系统",
    role: "Design System Lead / UI Design Lead",
    brief: "从 0 到 1 构建变量、组件、可视化编辑器、后台管理与治理流程。",
    image: "/assets/library/04-projects/01-wanying/cover/wanying.png",
    gallery: [
      "/assets/library/04-projects/01-wanying/gallery/设计变量-dark.png",
      "/assets/library/04-projects/01-wanying/gallery/Table表格.png",
      "/assets/library/04-projects/01-wanying/gallery/新增快速构建.png",
      "/assets/library/04-projects/01-wanying/gallery/新版首页.png",
      "/assets/library/04-projects/01-wanying/gallery/34e9d0d9-196c-4909-9559-1f01ba8fdd67.png",
    ],
    metrics: [["40+", "核心组件"], ["6", "系统模块"], ["30%", "重复设计减少"]],
    meta: { type: "企业级低代码平台", role: "设计系统主理 / UI 设计负责人", period: "2 年", status: "已上线 / 持续演进", year: "2021—2023" },
    overview: "一套支撑多业务线并行交付的低代码平台设计系统，覆盖变量、组件、可视化编辑器、管理后台与治理流程。",
    pains: [
      { tag: "PAIN 01", title: "标准分散", desc: "多业务线并行，界面风格不统一，每次新功能都在重复造轮子。" },
      { tag: "PAIN 02", title: "还原成本高", desc: "设计稿与代码命名脱节，研发反复确认才能落地，迭代缓慢。" },
      { tag: "PAIN 03", title: "组件被当资产", desc: "组件只存图，没有状态、边界与验收标准，无法真正复用。" },
    ],
    goal: "用一套统一的设计语言串起产品、设计与研发，让同一套命名既能描述界面，也能映射代码。",
    contribution: "独立负责设计系统整体规划与落地，完成 Token 体系、组件库、可视化编辑器与管理后台体验，并推动评审、命名与归档机制进入团队日常交付流程，方案最终落地为可持续演进的产品语言。",
    contributionTags: ["系统规划", "Token 体系", "组件库", "可视化编辑器", "管理后台", "设计治理"],
    contributionSplit: [
      { label: "系统规划与 Token", value: 22 },
      { label: "组件库设计", value: 30 },
      { label: "可视化编辑器", value: 24 },
      { label: "管理后台与治理", value: 24 },
    ],
    coreDesign: [
      { problem: "标准分散导致重复沟通", insight: "Token 是设计与代码的共同语言", solution: "按业务层级、组件状态与研发映射组织变量，让设计与代码用同一套命名描述界面。", impact: "重复沟通显著减少" },
      { problem: "组件只被当作视觉资产", insight: "组件是产品语言而非图片库", solution: "把组件沉淀为含使用场景、边界规则、交互状态与研发验收标准的可复用单元。", impact: "复用率提升" },
      { problem: "低代码能力难被普通用户理解", insight: "复杂配置要拆成肌肉记忆", solution: "重点处理拖拽吸附、属性同步、状态预览与发布，把复杂操作压成可学习路径。", impact: "上手门槛降低" },
    ],
    timeline: [
      { phase: "PHASE 01", title: "Token 体系", desc: "建立颜色 / 字体 / 间距 / 状态变量" },
      { phase: "PHASE 02", title: "组件库", desc: "沉淀 40+ 核心组件与状态规范" },
      { phase: "PHASE 03", title: "可视化编辑器", desc: "拖拽吸附 / 属性同步 / 发布" },
      { phase: "PHASE 04", title: "治理流程", desc: "评审 / 命名 / 归档进入日常交付" },
    ],
    stack: ["Figma", "Design Tokens", "React", "低代码引擎", "组件库"],
    capabilities: [
      { label: "系统思维", value: 95 },
      { label: "组件抽象", value: 90 },
      { label: "交互设计", value: 82 },
      { label: "视觉表达", value: 80 },
      { label: "研发协同", value: 88 },
    ],
    outcome: "完成从 Token、组件到编辑器与治理的完整闭环，沉淀 40+ 核心组件与 6 个系统模块，让设计系统成为持续演进的组织能力。",
    outcomeBars: [
      { label: "核心组件沉淀", value: 92, caption: "40+ 组件" },
      { label: "系统模块覆盖", value: 80, caption: "6 大模块" },
      { label: "重复设计减少", value: 70, caption: "约 30%" },
      { label: "研发协同效率", value: 85, caption: "命名对齐" },
    ],
    details: [
      ["背景", "多业务线并行开发，界面标准分散，设计还原与迭代成本持续升高。"],
      ["方法", "从 Token 切入，沉淀组件与核心交互，再建立评审、命名与归档机制。"],
      ["结果", "让设计系统从一次性交付变成持续演进、可被研发复用的组织能力。"],
    ],
  },
  {
    id: "admin",
    code: "ADMIN",
    type: "ENTERPRISE ADMIN CONSOLE",
    title: "企业级权限与流程管理平台",
    role: "Lead UI Designer",
    brief: "重构权限、组织架构、审批流程与数据表格体验。",
    image: "/assets/library/04-projects/02-admin/cover/admin.png",
    gallery: [
      "/assets/library/04-projects/02-admin/gallery/工作台.png",
      "/assets/library/04-projects/02-admin/gallery/业务逻辑.png",
      "/assets/library/04-projects/02-admin/gallery/数据模型设计器.png",
      "/assets/library/04-projects/02-admin/gallery/素材管理-图片-网格.png",
      "/assets/library/04-projects/02-admin/gallery/运维监控.png",
    ],
    metrics: [["12", "权限场景"], ["28", "页面模板"], ["22%", "路径缩短"]],
    meta: { type: "企业管理平台", role: "UI 设计主负责人", period: "6 个月", status: "已上线", year: "2023" },
    overview: "面向企业内部权限、组织架构、审批流程与数据表格体验的管理平台重构，把复杂管理任务拆成清晰、稳定、可学习的操作路径。",
    pains: [
      { tag: "PAIN 01", title: "权限交叉", desc: "角色与数据权限纠缠，用户常不清楚自己能做什么、为何被禁用。" },
      { tag: "PAIN 02", title: "信息层级松散", desc: "后台域多、入口分散，新老用户都容易在任务中迷路。" },
      { tag: "PAIN 03", title: "表格密度过高", desc: "高频操作埋在深层菜单，筛选与批量体验割裂。" },
    ],
    goal: "重组信息架构与角色路径，让管理动作有稳定、可预期的操作回路。",
    contribution: "独立负责管理后台的信息架构、权限矩阵、表格模式与异常状态设计，完成 28 个页面模板与 12 类权限场景的梳理与视觉落地，并主导与研发的验收对齐。",
    contributionTags: ["信息架构", "权限矩阵", "表格体系", "异常状态", "页面模板", "研发验收"],
    contributionSplit: [
      { label: "信息架构与权限", value: 30 },
      { label: "表格与表单体系", value: 28 },
      { label: "异常与状态设计", value: 22 },
      { label: "页面模板与验收", value: 20 },
    ],
    coreDesign: [
      { problem: "权限交叉导致误操作", insight: "权限要可见可解释", solution: "建立统一的权限矩阵与状态可视化，让用户始终清楚能做什么、为什么不能做。", impact: "误操作下降" },
      { problem: "表格密度高、操作路径深", insight: "高频动作压到两步以内", solution: "统一表格模式（筛选 / 批量 / 内联编辑 / 异常反馈），把高频操作压到两步以内。", impact: "路径缩短 22%" },
      { problem: "管理任务缺少可预期性", insight: "复杂任务要变成肌肉记忆", solution: "通过树状导航与稳定的状态流转，让复杂任务成为可被学习的操作路径。", impact: "学习成本降低" },
    ],
    timeline: [
      { phase: "PHASE 01", title: "信息架构", desc: "梳理后台域与角色路径" },
      { phase: "PHASE 02", title: "权限矩阵", desc: "统一 12 类权限场景与状态" },
      { phase: "PHASE 03", title: "表格体系", desc: "28 个页面模板与批量模式" },
      { phase: "PHASE 04", title: "异常与验收", desc: "异常反馈与研发对齐落地" },
    ],
    stack: ["Figma", "Axure", "React", "Ant Design", "ECharts"],
    capabilities: [
      { label: "信息架构", value: 92 },
      { label: "复杂表格", value: 90 },
      { label: "权限建模", value: 85 },
      { label: "异常设计", value: 82 },
      { label: "研发协同", value: 80 },
    ],
    outcome: "完成 12 类权限场景与 28 个页面模板的统一，关键路径缩短约 22%，让复杂管理任务变成稳定可学习的操作路径，平台已上线交付。",
    outcomeBars: [
      { label: "权限场景覆盖", value: 88, caption: "12 类场景" },
      { label: "页面模板沉淀", value: 82, caption: "28 个模板" },
      { label: "关键路径缩短", value: 65, caption: "约 22%" },
      { label: "操作可学习性", value: 86, caption: "稳定回路" },
    ],
    details: [
      ["背景", "后台域多、权限交叉、信息层级松散，新老用户都容易在任务中迷路。"],
      ["方法", "重组信息架构与角色路径，统一权限矩阵、表格模式和异常状态。"],
      ["结果", "复杂管理任务被拆成清晰、稳定、可学习的操作路径。"],
    ],
  },
  {
    id: "mobile",
    code: "MOBILE",
    type: "MOBILE PRODUCT / MINI PROGRAM",
    title: "移动端服务小程序体验升级",
    role: "Product Interface Designer",
    brief: "围绕查询、任务、消息与转化，重构移动端核心路径。",
    image: "/assets/library/04-projects/03-mobile/cover/mobile.png",
    gallery: [
      "/assets/library/04-projects/03-mobile/gallery/mobile.png",
      "/assets/library/04-projects/03-mobile/gallery/浅色外观-移动端.png",
      "/assets/library/04-projects/03-mobile/gallery/变量.png",
      "/assets/library/04-projects/03-mobile/gallery/新增快速构建.png",
    ],
    metrics: [["3", "核心人群"], ["18%", "入口点击提升"], ["2.4×", "路径更清晰"]],
    meta: { type: "移动端 / 小程序", role: "产品界面设计", period: "4 周", status: "已上线", year: "2024" },
    overview: "围绕查询、任务、消息与转化，重构移动端核心路径的服务小程序体验升级，让关键功能触达更短、回访更连贯。",
    pains: [
      { tag: "PAIN 01", title: "入口多层级深", desc: "功能散落在多级菜单，关键动作被埋没，转化被打断。" },
      { tag: "PAIN 02", title: "消息与任务割裂", desc: "通知与待办分属不同模块，回访后难以回到原有上下文。" },
      { tag: "PAIN 03", title: "人群差异大", desc: "新用户、老用户、运维人员路径需求不同，单一首页难以兼顾。" },
    ],
    goal: "以用户旅程为起点重排首页层级，让回访后能更快回到原有任务上下文。",
    contribution: "独立负责移动端核心路径的梳理与界面设计，围绕 3 类核心人群完成首页层级重排、任务入口统一与消息中心重构，并主导高保真原型与研发对接。",
    contributionTags: ["用户旅程", "信息架构", "首页重排", "任务入口", "消息中心", "高保真原型"],
    contributionSplit: [
      { label: "用户旅程与人群", value: 26 },
      { label: "首页层级重排", value: 30 },
      { label: "任务与消息统一", value: 24 },
      { label: "原型与研发对接", value: 20 },
    ],
    coreDesign: [
      { problem: "入口多层级深导致转化打断", insight: "关键动作回到首屏一步可达", solution: "以 3 类核心人群为起点重排首页层级，让关键动作回到首屏一步可达。", impact: "入口点击 +18%" },
      { problem: "消息与任务割裂", insight: "回访要能续接上下文", solution: "统一任务入口与消息中心，回访后直接回到原有任务上下文。", impact: "回访更连贯" },
      { problem: "回访路径不连贯", insight: "保留状态记忆", solution: "保留任务上下文与状态记忆，让再次进入像继续一段未完成的动作。", impact: "路径清晰度 ×2.4" },
    ],
    timeline: [
      { phase: "PHASE 01", title: "用户旅程", desc: "梳理 3 类核心人群与任务路径" },
      { phase: "PHASE 02", title: "首页重排", desc: "层级压缩 / 关键动作首屏化" },
      { phase: "PHASE 03", title: "任务与消息", desc: "统一入口与上下文续接" },
      { phase: "PHASE 04", title: "原型与对接", desc: "高保真原型与研发落地" },
    ],
    stack: ["Figma", "微信小程序", "Principle", "Rematch"],
    capabilities: [
      { label: "用户旅程", value: 90 },
      { label: "信息架构", value: 88 },
      { label: "移动交互", value: 92 },
      { label: "视觉表达", value: 78 },
      { label: "原型验证", value: 85 },
    ],
    outcome: "完成 3 类核心人群的路径重构，入口点击提升约 18%，路径清晰度提升 2.4 倍，关键功能触达更短并支持回访续接，小程序已上线。",
    outcomeBars: [
      { label: "入口点击提升", value: 72, caption: "约 18%" },
      { label: "路径清晰度", value: 90, caption: "×2.4" },
      { label: "人群路径覆盖", value: 78, caption: "3 类人群" },
      { label: "回访续接率", value: 84, caption: "上下文保留" },
    ],
    details: [
      ["背景", "功能入口多、层级深，消息与任务割裂，关键转化路径被打断。"],
      ["方法", "以用户旅程和 3 类核心人群为起点，重排首页层级并统一任务入口。"],
      ["结果", "关键功能触达更短，回访后能更快回到原有任务上下文。"],
    ],
  },
];

export const works = [
  { src: "/assets/library/05-graphic/三星堆海报.jpg", title: "三星堆", type: "POSTER / CULTURE" },
  { src: "/assets/library/05-graphic/湘遇好礼海报.jpg", title: "湘遇好礼", type: "BRAND / CAMPAIGN" },
  { src: "/assets/library/05-graphic/佛像海报.jpg", title: "造像", type: "POSTER / CULTURE" },
  { src: "/assets/library/05-graphic/个人工作站loading页.jpg", title: "个人工作站", type: "MOTION / LOADING" },
  { src: "/assets/library/05-graphic/Frame 1041253.jpg", title: "视觉试验", type: "GRAPHIC / EDITORIAL" },
  { src: "/assets/library/05-graphic/image 134.jpg", title: "图形档案", type: "GRAPHIC / SYSTEM" },
  { src: "/assets/library/05-graphic/Frame 1041254.jpg", title: "版式练习", type: "EDITORIAL / TYPE" },
  { src: "/assets/library/05-graphic/Group 1321316532.jpg", title: "视觉切片 01", type: "GRAPHIC / ARCHIVE" },
  { src: "/assets/library/05-graphic/Group 1321316534.jpg", title: "视觉切片 02", type: "GRAPHIC / ARCHIVE" },
  { src: "/assets/library/05-graphic/Group 1321316535.jpg", title: "视觉切片 03", type: "GRAPHIC / ARCHIVE" },
  { src: "/assets/library/05-graphic/Group 1321316536.jpg", title: "视觉切片 04", type: "GRAPHIC / ARCHIVE" },
  { src: "/assets/library/05-graphic/Group 1321316537.jpg", title: "视觉切片 05", type: "GRAPHIC / ARCHIVE" },
  { src: "/assets/library/05-graphic/image 118.jpg", title: "影像实验", type: "IMAGE / STUDY" },
  { src: "/assets/library/05-graphic/image 138.jpg", title: "材质档案", type: "IMAGE / STUDY" },
];

export const vibeProjects = [
  {
    index: "01", code: "X-GZ", title: "小小馆长", subtitle: "成长记录 / 藏品策展 / 睡眠故事",
    tags: "WECHAT MINI-PROGRAM · AI · FAMILY", image: "/assets/library/06-vibe/01-xiaoxiaoguanzhang/audio-lab.png", mediaType: "image",
    wechat: { qr: "/assets/library/06-vibe/01-xiaoxiaoguanzhang/qrcode.png", hint: "微信搜索「小小馆长」立即体验" },
    description: "把孩子喜欢的东西变成博物馆藏品，基于藏品生成专属睡眠故事，支持童言、第一次、日志与策展记录。",
    background: "传统成长记录靠相册与日记，素材零散、缺少故事性，孩子的好奇心与童言随时间遗忘，无法被结构化保存与回看。",
    problem: "成长记录碎片化：照片散落相册，童言与第一次靠记忆，缺少把孩子视角的收藏转化为可回看、可策展叙事的工具。",
    solution: "以藏品为核心，记录童言、第一次与日常日志，AI 基于藏品生成专属睡眠故事，支持 3D 化藏品与访问朋友博物馆。",
    stack: ["微信小程序", "Three.js", "LLM API", "云开发"],
    highlights: ["藏品化记录孩子喜好", "基于藏品生成专属睡眠故事", "童言 / 第一次 / 日志结构化沉淀", "3D 藏品与跨朋友博物馆互访"],
    link: "#",
  },
  {
    index: "02", code: "V-ALC", title: "声纹炼金炉", subtitle: "人声训练 / 声纹替换 / 母带翻唱",
    tags: "WEB AUDIO · AI VOICE · ENTERTAINMENT", image: "/assets/library/06-vibe/02-travel-archive/travel-archive.png", mediaType: "image",
    description: "PC 端网页娱乐工具，训练个人人声模型，对歌曲提取人声、声纹替换并后期母带，生成翻唱作品。",
    background: "想用自己的声音翻唱喜欢的歌，但传统流程要在宿主软件里手动对轨、调效果器，还需要本地部署 AI 模型，门槛高且碎片化。",
    problem: "翻唱链路割裂：人声提取、声纹训练、替换、母带各用不同工具，参数无法互通，普通用户难以独立完成一首翻唱。",
    solution: "在浏览器内串联人声训练→歌曲分离→声纹替换→母带后期→导出全流程，每步参数保留可回溯，降低翻唱门槛。",
    stack: ["React", "Web Audio API", "Python AI", "FFmpeg.wasm"],
    highlights: ["录制并训练个人人声模型", "一键分离歌曲人声与伴奏", "声纹替换实时预览对比", "母带后期与多版本导出"],
    link: "#",
  },
  {
    index: "03", code: "M-HANG", title: "墨航 · 文学实验室", subtitle: "小说创作 / AI 自动写作 / 本地优先",
    tags: "AI · LITERATURE · FULL-STACK", image: "/assets/library/06-vibe/03-pixel-alchemy/pixel-alchemy.png", mediaType: "image",
    description: "面向创作者的小说创作工作台，整合项目管理、创作中心、PRD 文档与 AI 自动写作，本地优先、数据自持。",
    background: "写作者在使用通用文档工具时，创作素材、大纲、设定、章节散落各处，AI 辅助写作只能片段生成，无法贯穿整本小说的设定与连续性。",
    problem: "创作工具割裂：项目管理、正文写作、设定维护与 AI 生成各用一套，设定无法跨章节复用，AI 不理解既有世界观，长篇连贯性难维护。",
    solution: "以工作台为核心，整合小说项目、创作中心、PRD 文档与设置，AI Agent 基于本地设定自动续写，保证世界观一致与创作链路完整。",
    stack: ["React", "Node.js", "SQLite", "LLM API"],
    highlights: ["工作台统一管理多本小说项目", "创作中心与设定文档联动", "AI Agent 基于本地设定自动续写", "本地优先，数据自持可离线"],
    link: "https://mohang.zenslab.top",
  },
  {
    index: "04", code: "S-LJ", title: "食旅集", subtitle: "菜单识别 / 可视化点单 / 跨语言点餐",
    tags: "AI · TRAVEL · FULL-STACK", image: "/assets/library/06-vibe/04-shilvji/image-bureau.png", mediaType: "image",
    description: "拍下外文菜单，AI 识别分类、匹配图片、换算价格，生成可视化中文点单界面。",
    background: "去国外旅行吃饭时，菜单全是外文，菜名看不懂、价格要换算、不知道长什么样，只能靠猜或随便指，点餐体验紧张又低效。",
    problem: "语言障碍 + 信息缺失：外文菜名无法理解，缺少菜品图片参考，价格需心算换算，点完无法确认，与服务员沟通成本高。",
    solution: "拍下菜单 → AI 识别菜品并分类 → 自动搜索对应图片 → 生成带中文名、换算价格的可视化菜单 → 勾选提交小票单，全程不靠口语沟通。",
    stack: ["React", "Node.js", "OCR / Vision API", "Tailwind"],
    highlights: ["菜单拍照即识别分类", "自动匹配菜品参考图", "中文名称与汇率换算价格", "点单小票一键提交服务员"],
    link: "https://slj.zenslab.top",
  },
];
